### ISSUE TITLE
Issues with running bludit locally

### ISSUE THREAD

**Issue by 1Seann** [dignajar/bludit#1]
I have been facing issues while trying to run bludit on localhost. It seems to be something to do with the .htaccess file as commenting out "RewriteEngine on" allows the folder to be accessed but nothing else can be done even with "rewrite_module" enabled. 

Tested on the following: 
- WAMP
- Uniform Server Z
- XAMPP

**Comment by syndicatefx** [comment]
I think it's the same problem/issue with **this repo** as i stated on [#2](https://github.com/dignajar/bludit/issues/2), try downloading and using [bludit_latest.zip](http://www.bludit.com/bludit_latest.zip) and see if you face the same issues.

**Comment by 1Seann** [comment]
Even after attempting to run the latest version on WAMP it reaches the install.php and once that is completed it shows a blank page. Even used the two commands stated in #3.

**Comment by dignajar** [comment]
Fixed! try the latest files from Github. thanks

**Comment by acrox999** [comment]
Seems to be fixed but it won't work properly unless the trailing slash in turned on in the .htaccess.

**Comment by dignajar** [comment]
I removed the trailing slash in the file .htaccess.
