### ISSUE TITLE
Position mainpage

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#100]
If the mainpage (home) is not created as the first page, the position has to be 0 to be shown on top of the navigation in the sidebar (plugin Pages).

**Comment by dignajar** [comment]
Yes I know, but, I don't like the position 0, it a valid position for developers (arrays, etc..) but for the simple user doesn't.

**Comment by clickwork-git** [comment]
Yes, I know. But it only works with 0, when other pages are yet created. How to fix it?

**Comment by dignajar** [comment]
Sorry for the delay, I don't understand, could you give me an example to reproduce this ? thanks

**Comment by clickwork-git** [comment]
You can reproduce it as follows:

1) Install Bludit.
2) Add a page "Mainpage" (set position 1, set page "About" to position 2).
3) Add a page "Page" (set position 3).
4) Add a page "New mainpage" (set position 1).
5) Set "Mainpage" to position 4.

**Comment by dignajar** [comment]
I saw the problem, I will fix it.

**Comment by dignajar** [comment]
FIxed, could you try if the pages are order by position ?

**Comment by clickwork-git** [comment]
Works now.

**Comment by dignajar** [comment]
ok, I close the topic.
