### ISSUE TITLE
Profile image upload

### ISSUE THREAD

**Issue by nickbe** [dignajar/bludit#114]
Uploading the profile image (using php -S localhost:80) does currently not work.

Bludit tries to access the folder: content\uploads\profiles which does not exist.
After creating the folder I can upload the image.

Is there a template yet that displays the profile image?

**Comment by dignajar** [comment]
Hi,
yes it a bug when you upgrade your Bludit, because this latest version the installer create the directory content/uploads/profiles.

**Comment by anaggh** [comment]
Yup, I can confirm this bug. I could'nt upload a picture after updating from 0.5 to 0.6.1 on the browser.

Had to do this to fix it.

    mkdir /var/www/html/blog/content/uploads/profiles
    chown -R www-data:www-data /var/www/html/blog/content

**Comment by dignajar** [comment]
I made an updater for this cases, it pushed in github, thanks!
