### ISSUE TITLE
Error after updating.

### ISSUE THREAD

**Issue by anaggh** [dignajar/bludit#116]
Updated from 0.5 to 0.6.1 
I downloaded a fresh copy of 0.6.1 and copied the content dir from 0.5 to 0.6.1

In Settings -> Language and timezone, this error is shown.

    Notice: Undefined index: language-data in /var/www/html/blog/kernel/dblanguage.class.php on line 98

Line 98 has the following just for reference.

    $native = $t->db['language-data']['native'];

**Comment by dignajar** [comment]
Hi, there is a error on the Hebrew language file, delete this files or upgrade from github.

**Comment by dignajar** [comment]
I made a catch for this cases, it pushed on github. Thanks

**Comment by anaggh** [comment]
Thanks. Deleted he_IL.json and error has been fixed.
