### ISSUE TITLE
Plugin Opengraph: problem with og:image

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#129]
<meta property="og:image" content=""> is always empty an gives an error message when testing with the Facebook debugger:

https://developers.facebook.com/tools/debug/

Works without the meta tag.

**Comment by clickwork-git** [comment]
Adding something like this do retrieve the linked image and define the image url for OG could do it:

    $content = $Post->content();
    $sstring1 = '/content/uploads/';
    $pos1 = strpos($content,$sstring1);
    $string1 = substr($content, $pos1);
    $sstring2 = '.';
    $pos2 = strpos($string1,$sstring2);
    $string2 = substr($string1, 0, $pos2+4);
    $url = $Site->url();
    $imgurl = $url;
    $imgurl .= $string2;

Im not very good in PHP, but it works. Perhaps it could be coded more elegant.

**Comment by dignajar** [comment]
I will work on it, thanks.
