### ISSUE TITLE
TinyMCE does not work with polish interface

### ISSUE THREAD

**Issue by kaaleth** [dignajar/bludit#154]
Hi,

TinyMCE does not show form for posts and pages in polish interface. I used validator for json files but it did not find any errors. That is weird because editor works fine with english or other language(s).

**Comment by dignajar** [comment]
Hi,
I made some change on the plugin, and upgrade to TinyMCE 4.3.1.
I made a change on this file too https://github.com/dignajar/bludit/blob/master/kernel/abstract/plugin.class.php

**Comment by kaaleth** [comment]
I did upgrade to the latest version but this problem still exists. Do you think that issue is about polish language or system? I checked file without any errors but other languages works fine.

**Comment by dignajar** [comment]
try to download all files from github, and make a new installation.

**Comment by kaaleth** [comment]
After new installation works fine...

but it would be great to fix this after upgrade method.

**Comment by dignajar** [comment]
You update this file too ? https://github.com/dignajar/bludit/blob/master/kernel/abstract/plugin.class.php

**Comment by kaaleth** [comment]
@dignajar 

I did full upgrade and nothing happend. After that, I did backup and reinstall whole cms.

**Comment by dignajar** [comment]
It's very strange, could you try making a hard refresh on your browser? CTRL+SHIFT+R

**Comment by clickwork-git** [comment]
Perhaps a problem with the character set. The language files of TinyMCE are not UTF-8.

**Comment by clickwork-git** [comment]
Seems not to be a charset problem. Had the problem with version 0.7, was gone after updating to version 0.7.2.

**Comment by kaaleth** [comment]
@dignajar I already told you, my blog was reinstalled to the newest version so I can't try your solution.

Problem is solved but when someone is going to upgrade, it might be problem.
