### ISSUE TITLE
Small issue with pretty URL

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#157]
Pretty URL cannot be "plugins". This gives an error message.

It happens if there is no parent page. If there is a parent page it works.

**Comment by dignajar** [comment]
Which web server are you using ?

**Comment by clickwork-git** [comment]
It's on different Apache installations:

Apache/2.2.31 FreeBSD
Apache/2.2.22 Debian
Apache/some Linux

**Comment by dignajar** [comment]
I think if you have problem with plugins, you will have problem with any folder name from Bludit, for example languages, kernel ?

**Comment by clickwork-git** [comment]
Yes, this is it!

**Comment by dignajar** [comment]
Fixed with the directive, DirectorySlash Off, in the .htaccess.
