### ISSUE TITLE
Google cuts title

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#162]
I encountered a strange problem (not sure if it is Bludit related): Google cuts a title when using ". I cannot see any problem with the format of the title.

![2015-12-23 00_08_21-bludit - google-suche](https://cloud.githubusercontent.com/assets/14312561/11968251/8cca4ece-a90a-11e5-966f-05fa79a906e8.png)

**Comment by clickwork-git** [comment]
I found the following explanation:

http://webmasters.stackexchange.com/questions/86507/google-cuts-my-page-title-on-search-results/86511

I use the theme pure. The title of a post is h2. I think it should be h1.

**Comment by dignajar** [comment]
Interesting, I will check this. thanks

**Comment by dignajar** [comment]
I made the change for the Pure theme, but I need to check others themes

**Comment by dignajar** [comment]
Can I close this issues?

**Comment by clickwork-git** [comment]
Yes, we can close it.
