### ISSUE TITLE
"Advanced":

### ISSUE THREAD

**Issue by rayblo** [dignajar/bludit#163]
IN the lang file on row 45 "Advanced": should be written as "advanced":
This is how its used in the code otherwise translation will not work

**Comment by dignajar** [comment]
Hi, in wich language file ?

**Comment by rayblo** [comment]
Well it's in the English language file so anyone who will translate that it will nog work in any file

**Comment by dignajar** [comment]
I don't see the Advanced (with the capitalize letter) in the English file, https://github.com/dignajar/bludit/blob/master/languages/en_US.json

**Comment by rayblo** [comment]
It's spelled with the lower a. So advanced "Advanced"
But to fix it I have placed in the nl_NL file Advanced "Geavanceerd to translate the word into dutch

**Comment by dignajar** [comment]
Fixed!
