### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by xannonmedia** [dignajar/bludit#170]
I get this error whilst performing a fresh install.   Any Ideas?

Notice: date_default_timezone_set() [function.date-default-timezone-set]: Timezone ID '' is invalid in /home/meganlou/public_html/blog/kernel/dbsite.class.php on line 252

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct() [<a href='datetime.--construct'>datetime.--construct</a>]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'UTC' for 'AWST/8.0/no DST' instead' in /home/meganlou/public_html/blog/kernel/helpers/date.class.php:14 Stack trace: #0 /home/meganlou/public_html/blog/kernel/helpers/date.class.php(14): DateTime->__construct() #1 /home/meganlou/public_html/blog/kernel/dbposts.class.php(388): Date::current('Y-m-d H:i:s') #2 /home/meganlou/public_html/blog/kernel/boot/rules/70.posts.php(122): dbPosts->regenerateCli() #3 /home/meganlou/public_html/blog/kernel/boot/site.php(4): include('/home/meganlou/...') #4 /home/meganlou/public_html/blog/index.php(39): require('/home/meganlou/...') #5 {main} thrown in /home/meganlou/public_html/blog/kernel/helpers/date.class.php on line 14

**Comment by dignajar** [comment]
Hi, where you get this error, before, after the installation ?

**Comment by xannonmedia** [comment]
Hello,

during installation, after about 2 steps.

Thanks,
Aaron

**Comment by dignajar** [comment]
Sorry for my late answer, where do you executed Bludit, in a private server or some hosting ? I want to try on it to get the error.

**Comment by xannonmedia** [comment]
It's hosted on a server with crazydomains

**Comment by dignajar** [comment]
I made some changes on the code, could you check now ? thanks

**Comment by dignajar** [comment]
Can I close the issues ?

**Comment by xannonmedia** [comment]
i will test the new code over the next 2 days and get back to you :)

thanks

**Comment by dignajar** [comment]
Feel free to open a new issues. thanks

**Comment by xannonmedia** [comment]
Issue is fixed, thanks.
