### ISSUE TITLE
Image Selection not working anymore

### ISSUE THREAD

**Issue by nickbe** [dignajar/bludit#179]
I don't get it. I'm on windows - Using Apache. So far everything worked fine.

Until recently selecting an image was the easiest thing ever.
Now the old "add image to article" button is gone. Why?

**Comment by dignajar** [comment]
Hi, you are running Bludit from Github ? I made some change on images system, I remove the select and add thumbnails.

**Comment by nickbe** [comment]
Yes I did. the Thumbnails are quite nice, but when inserting them it didn't work.

Cheers
Nick

**Comment by dignajar** [comment]
Maybe there are some bugs, the version from Github are very unestable, just for testing..

**Comment by dignajar** [comment]
What editor are you using ? Tinymce is not supported for the moment the new system of images.

**Comment by nickbe** [comment]
The SimpleMDE default editor.

**Comment by nickbe** [comment]
Ok, now I get it. If I doubleclick on an image then you create the correct image link. But if I drag/drop an image then you create the wrong html link including the URL base, which bludit does not seem to like at all. I think both ways should work though.

Also if I doubleclick an image than the link is always inserted at the end of the article, even I the cursor was somewhere else.

**Comment by dignajar** [comment]
The drag and drop doesn't work as expected but is good idea, for the moment I disabled drags and drop action the thumbnails.

SimpleMDE doesn't have the features to insert content where you have focus on the content, you can create a issues on there Github https://github.com/NextStepWebs/simplemde-markdown-editor
