### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by Turqueso** [dignajar/bludit#180]
does it has this function or are the re plan for it in the near feature?

**Comment by dignajar** [comment]
Recently I uploaded the plugin for sitemap... working on RSS

**Comment by Turqueso** [comment]
@dignajar Glad to read that, thanks!

**Comment by dignajar** [comment]
New plugin implemented for RSS, when you have some time, try it. thanks

**Comment by Turqueso** [comment]
@dignajar I would like to try the RSS plugin but I can't find it on the repo for plugins?

**Comment by Turqueso** [comment]
Activated the plugin and got this
`Notice: Use of undefined constant DOMAIN_BASE - assumed 'DOMAIN_BASE' in /home/vitaeure/public_html/test/blog/plugins/rss/plugin.php on line 81`

**Comment by dignajar** [comment]
Just work with the latest version from Github, today I will release the new version with the plugin
