### ISSUE TITLE
index.php in url gives an error

### ISSUE THREAD

**Issue by gaurav-chandra** [dignajar/bludit#183]
If you have a url like:
```
https://www.nstuts.net/index.php
```
the system gives an error page but if you remove the index.php from url, the system is going to home page.

If I have index.php in url, like above, it should automatically go to home page.

**Comment by dignajar** [comment]
Yes I know, this is bad ? could you give some example of uses? thanks

**Comment by gaurav-chandra** [comment]
Many times, via google search, the user is landing at https://www.nstuts.net/index.php instead of https://www.nstuts.net/ and it shows the error. 

The index.php is the main entry point for the web app so automatically it should show the home page and not the error.

**Comment by dignajar** [comment]
This is strange, the part when Google linked a page doesn't exist. The
entry point could be, index.htm, index.html, index.php, index.asp, this
depends of the web-server.

**Comment by gaurav-chandra** [comment]
I had to change the code in ```\kernel\boot\rules\70.pages.php``` file.

###Old Code
```
if($Url->notFound())
{

        $Url->setWhereAmI('page');
        $Page = new Page('error');

}
```

###New Code
```
if($Url->notFound())
{
    header("Location: https://www.nstuts.net/");
    exit;

        /*$Url->setWhereAmI('page');
        $Page = new Page('error');*/

}
```
Now any not found url is redirected to the non index.php url.
