### ISSUE TITLE
Feature request: Autosave

### ISSUE THREAD

**Issue by anaggh** [dignajar/bludit#184]
While writing a post/page, the input should be saved to drafts at frequent intervals to prevent data loss if in case the browser crashes/user mistakenly closes the tab/browser.

Would be very useful. I lost an article I typed for an hour by mistakenly closing the tab.

**Comment by acrox999** [comment]
I second this, I lost a whole article while writing it on Microsoft Edge. This browser sometimes randomly refreshes web pages, but I still like it.

**Comment by nickbe** [comment]
I think SimpleMDE already has that capability. Why not simply using it?
We could activate/deactivate this in the settings. And I agree that if you're writing long posts you certainly feel good about not going to loose something because of a stupid firefox crash, or provider interrupt.

**Comment by dignajar** [comment]
I enable the feature from Simplemde, it works fine.

**Comment by nickbe** [comment]
Great. It's gonna be a good think for authors if they don't have to worry about this anymore :)

**Comment by dignajar** [comment]
Implemented on the latest version 1.1. I close the topic, feel free to open a new issues.
