### ISSUE TITLE
Issue with latest version an theme

### ISSUE THREAD

**Issue by nickbe** [dignajar/bludit#186]
The Method: Post::authorFirstName does not seem to work anymore. Most of the themes are broken now :(.

![unbenannt](https://cloud.githubusercontent.com/assets/10890765/12276922/ca951b2a-b978-11e5-817e-dbd0d67b1e28.png)

**Comment by clickwork-git** [comment]
It works for me with Pure. Not with Future Imperfect and Busines Casual. It is not broken, but shows the username instead of first and last name.

**Comment by dignajar** [comment]
Yes, I deleted the method authorFirstName. The themes doesn't work with the latest version from github, Github version is just a beta version.
