### ISSUE TITLE
DirectorySlash Off breaks install.php auto-detection

### ISSUE THREAD

**Issue by acrox999** [dignajar/bludit#192]
It seems that the new entry in .htaccess since 1.0-beta1, "DirectorySlash Off" breaks auto-detection of install.php on fresh installations.

Tested on XAMPP 7.0.1 and also a live host.

**Comment by clickwork-git** [comment]
Do you mean the same as described in issue #194? Or what exactly do you mean?

**Comment by acrox999** [comment]
I'm not sure. I was able to install just fine when I set DirectorySlash On. When it's Off, it won't auto load install.php. On and it will auto load.

**Comment by dignajar** [comment]
I made a little change on the installer, could you check if now detect the language ? please try with the option DirectorySlash Off on the .htaccess

**Comment by dignajar** [comment]
Do you mean the auto-detection language or another auto-detection ?

**Comment by acrox999** [comment]
Not language, but the actual install.php itself won't automatically load. I
have to add a "/" at the end of the url for it to load install.php.

After installation it does work fine with DirectorySlash Off however.

**Comment by acrox999** [comment]
I spoke too soon. I tried again with DirectorySlash Off, and index.php isn't loading automatically either (shows directory tree instead) after installing.

**Comment by acrox999** [comment]
This happens on Firefox and Edge (doesn't load install,php and index.php after installation, have to add trailing slash after URL to actually load them). Chrome works fine.

**Comment by dignajar** [comment]
Yeap, it a problem with DirectorySlash off, I take off from .htaccess, I will think in another solution.

**Comment by dignajar** [comment]
I close the issues, I removed the option from the .htaccess. Thanks for reported it.
