### ISSUE TITLE
Bug: /admin/themes does not show the default theme: pure

### ISSUE THREAD

**Issue by anaggh** [dignajar/bludit#193]
Bludit version: Bludit v1.0 BETA 1

Returns an empty table

**Comment by clickwork-git** [comment]
Also additional themes are not listed.

**Comment by dignajar** [comment]
I see both themes, pure and future-imperfect, do you make a clean installation ?

**Comment by dignajar** [comment]
I forgot to update the theme Pure on Github, now is updated.

**Comment by clickwork-git** [comment]
Oops, and I used an old version of Furture Imperfect.

The update is not yet on GitHub.

**Comment by anaggh** [comment]
Thanks. Fixed on the Github version. Closing this.
