### ISSUE TITLE
Language selection does not work

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#194]
The language selection in the installation process does not work with v. 1.0 Beta 1.

**Comment by clickwork-git** [comment]
Seems to be $Language->get(); that does not work. $_GET['language']; is okay.

**Comment by clickwork-git** [comment]
The problem is caused by the following in install.php (line 119):

```
if( !Sanitize::pathFile(PATH_LANGUAGES.$localeFromHTTP) ) {
	$localeFromHTTP = 'en_US';
}
```

**Comment by dignajar** [comment]
Little mistake. With this should work.

```
if( !Sanitize::pathFile(PATH_LANGUAGES.$localeFromHTTP.'.json') ) {
	$localeFromHTTP = 'en_US';
}
```

**Comment by clickwork-git** [comment]
Thank you, this works!

**Comment by clickwork-git** [comment]
But it is not yet implemented on GitHub.

**Comment by clickwork-git** [comment]
Now on GitHub.
