### ISSUE TITLE
Admin CP page is 404'd

### ISSUE THREAD

**Issue by 1Seann** [dignajar/bludit#2]
Upon installation we are pointed to **/admin** which seems to be missing or fails to rewrite its path.
If any changes are to be made the user has to access **/admin/dashboard**.

**Comment by syndicatefx** [comment]
That's strange, upon installation you should be pointed to the homepage with the "first post" displayed and from there access **admin/**. If you can see the homepage but fail to get into **/admin** check to see if you have mod_rewrite enabled.

There are issues with file/folder permissions on **this repo**, on my localhost setup i have to change permissions for all folders recursively to 777 just to get into install. Try downloading the latest.zip from [bludit.com](http://bludit.com), that version worked for me out of the box.

**Comment by dignajar** [comment]
Login -> /admin/
Login -> /admin/login
Dashboard -> /admin/dashboard
