### ISSUE TITLE
Feature request: SPAM prevention for email-adresses in posts and pages

### ISSUE THREAD

**Issue by HarleyDavidson86** [dignajar/bludit#201]
It would be nice if there's a function to convert email-adresses in HTML ASCII-Code in the editor so they are not readable in the sourcecode of the website.

Here's my proposal:
http://forum.bludit.com/viewtopic.php?f=14&t=195

**Comment by dignajar** [comment]
Hi, nice feature, may be for implement a plugin for it, I will check, thanks

**Comment by HarleyDavidson86** [comment]
Hi, I implemented a plugin and already created a pull request for the plugin-repository
