### ISSUE TITLE
Error when installing (PHP 5.3)

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#206]
When installing with PHP 5.3 I get the error:

Fatal error: Can't use method return value in write context in /var/www/web597/html/bludit/bl-plugins/disqus/plugin.php on line 36

The error is caused by:

```
if( !empty($Site->homePage()) ) {
    $this->disable = true;
}
```

The following works with PHP 5.3:

```
$hp = $Site->homePage();
if (!empty($hp)) {
    $this->disable = true;
}
```

http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context

**Comment by danteoms** [comment]
It worked. thank you :+1:

**Comment by dignajar** [comment]
Fixed, I used the Helper from Bludit.

```
if( Text::notEmpty($Site->homePage()) ) {
    $this->disable = true;
}
```
