### ISSUE TITLE
Update problem: missing navigation

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#208]
When switching from Pure to Blogme after updating from v0.7.2 to v1.0 the sidebar with the navigation is missing.

But perhaps this is a misunderstanding because its a blog theme: This happens only with pages (also with a fresh installation).

**Comment by acrox999** [comment]
Permalink pages (both posts and pages) won't show the sidebar. Since this theme is based on Future Imperfect, and is made by Diego himself perhaps that is how he intended it to be.

**Comment by dignajar** [comment]
Yeap, the posts and pages doesn't have navigator bar, but you can enable it, remove the lines 33 and 40, from the file blogme/index.php
