### ISSUE TITLE
Feature request: Warning when plugin is not compatible or not tested

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#219]
I think, this is possible with the new metadata field "requires": If a plugin is not compatible with a version or not yet tested a warning is shown.

**Comment by dignajar** [comment]
It's good idea, but I think there need another field, because this field "requires" has text, and the user can put any text and is difficult to compare.

**Comment by acrox999** [comment]
I like this idea and comparing the text wouldn't be too much of a big issue, in my opinion. The warning will be shown regardless and that just shows the carelessness of the plugin's author.
