### ISSUE TITLE
Feature request: SVG images support 

### ISSUE THREAD

**Issue by HarleyDavidson86** [dignajar/bludit#220]

**Comment by clickwork-git** [comment]
What exactly do you mean? Upload? Use in post and pages?

**Comment by HarleyDavidson86** [comment]
Yes, upload and usage in pages and posts.
At this time I get a message when try to upload a svg file.
At this moment, only jpg, jpeg, png and gif are supported.
It only works when I upload the image and insert the link to it manually.

**Comment by dignajar** [comment]
Do you know how to handle svg with PHP ? resize, crop, etc..

**Comment by HarleyDavidson86** [comment]
I think I can handle this.
Let's give it a try.

**Comment by HarleyDavidson86** [comment]
I implemented this feature. At least it was not that hard than I thought ;)
See my pull request.

**Comment by alexandreteles** [comment]
@dignajar #328 was merged and solve this issue. I think it's time to close it?

**Comment by HarleyDavidson86** [comment]
Thanks for applying my suggestion!
