### ISSUE TITLE
Rewrite in .htaccess

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#221]
To deny direct access to .txt files

`RewriteRule ^content/(.*)\.txt$ - [R=404,L]`

should be replaced with

`RewriteRule ^bl-content/(.*)\.txt$ - [R=404,L`

**Comment by dignajar** [comment]
Yes, an user made the change. https://github.com/dignajar/bludit/commit/bdd594da0c9194bb4e759494031488c828452101

**Comment by clickwork-git** [comment]
Okay, he posted it also in the forum.
