### ISSUE TITLE
minor: maintenance plugin - Custom message resets after enabling-disabling-enabling mode

### ISSUE THREAD

**Issue by CryssDOTnet** [dignajar/bludit#224]

**Comment by acrox999** [comment]
If you actually meant disabling/enabling via the plugins menu (Activate/Deactivate) and not inside the plugin's own configuration page (Enable maintence mode checkbox) then it will lose the configuration, not only for this plugin but all.

Deactivating a plugin will remove its configuration from the database.

**Comment by dignajar** [comment]
Yes, for this particular plugin it's not the best approach. As say acrox999, when you disable a plugin this delete the database.

**Comment by dignajar** [comment]
In the plugin Maintenance you have a checkbox to enable or disable the plugin, without deactivate it and delete the database.
