### ISSUE TITLE
Feature request: Ability to add meta description and meta keywords on post and page

### ISSUE THREAD

**Issue by gaurav-chandra** [dignajar/bludit#226]
Ability to add meta description and meta keywords on post and page along with title of the page. I was trying to create a plugin but I was unsuccessful due to lack of plugin documentation.

**Comment by clickwork-git** [comment]
This is yet implemented. The field "Desccription" is used for the meta description, the field "Tags" also for meta keywords.

But keywords are no longer supported by Google. Therefore this meta information is deprecated.

**Comment by dignajar** [comment]
Edi is right, but may be there themes where is missing this meta tags.. If I create a plugin for meta tags, in each theme, will be necesarry delete them..

**Comment by gaurav-chandra** [comment]
Figured out a way:

```
head.php
<title><?php
    if (($Url->whereAmI() == 'home') || ($Url->whereAmI() == 'tag') || ($Url->whereAmI() == 'blog')) {
        echo $Site->title();
    } elseif ($Url->whereAmI() == 'post') {
        echo $Post->title();
    } elseif ($Url->whereAmI() == 'page') {
        echo $Page->title();
    }
    ?></title>

<meta name="description" content="<?php
if (($Url->whereAmI() == 'home') || ($Url->whereAmI() == 'tag') || ($Url->whereAmI() == 'blog')) {
    echo 'Gaurav Chandra, a Freelance mobile application developer based in Delhi NCR (Noida). Hire me to develop mobile apps for your business.';
} elseif ($Url->whereAmI() == 'post') {
    echo $Post->description();
} elseif ($Url->whereAmI() == 'page') {
    echo $Page->description();
}
?>">
```

This works for me. Even my SEO guys says that this is fine. Keywords are not put anymore due to changes in google's algorithm.

**Comment by dignajar** [comment]
I added to the helper the ability to add the title and the description. I used it on the themes pure, future imperfect and blogme, the developers of themes need to add this features.
