### ISSUE TITLE
Bug: Not able to delete an applied tag during post writing

### ISSUE THREAD

**Issue by gaurav-chandra** [dignajar/bludit#229]
If I accidentally apply a tag during writing a post, there is no way I can delete it.

**Comment by acrox999** [comment]
I think you should be able to by clicking on them.

**Comment by gaurav-chandra** [comment]
aah yes, but this is not intuitive. To remove, there should be a cross icon or something along with the click feature.

**Comment by acrox999** [comment]
Yes, indeed. A simple HTML/CSS fix will do.

**Comment by dignajar** [comment]
I'm working on the tags.. to be more intuitive..

**Comment by dignajar** [comment]
Done, check the version from Github, this has new system tags.

**Comment by dignajar** [comment]
Implemented on the latest version 1.1. I close the topic, feel free to open a new issues.
