### ISSUE TITLE
Flatboard Issue

### ISSUE THREAD

**Issue by nickbe** [dignajar/bludit#246]
Since I don't know where to put this:
I just tried flatboard, but there are issues when trying to run this in windows:

href to css is written as:    .\theme\kube\cache\core.min.css?ver=0.7.5_Beta
but should be /theme/kube/cache/core.min.css?ver=0.7.5_Beta

**Comment by clickwork-git** [comment]
You have to address this to the flatboard developer:

http://flatboard.co.nf
https://github.com/Fred89/flatboard
https://gitter.im/Fred89/flatboard

**Comment by dignajar** [comment]
You can try on the forum too. https://forum.bludit.com

@Fred89 it's the developer.
