### ISSUE TITLE
Pure Theme pagebreak issue

### ISSUE THREAD

**Issue by danielyf** [dignajar/bludit#247]
Hello, I noticed that  "" cuts the post in the new Pure theme, when you click "Read more" it doesn't display more text.

**Comment by dignajar** [comment]
Fixed!

**Comment by dignajar** [comment]
If you want update this file on your web server, https://github.com/dignajar/bludit/blob/master/bl-themes/pure/php/post.php

**Comment by danielyf** [comment]
Wow! That was impressively fast!!.

I downloaded the file with wget, should I chmod it?

**Comment by danielyf** [comment]
I did:
find . -type d | xargs chmod 750
find . -type f | xargs chmod 660

In the Bludit directory, should it be enough?


Also, I forgot about the most important think: Thank you so much for your impresive CMS, and the fix!

**Comment by dignajar** [comment]
The permissions are ok, but you need to check what user is running your
webserver, then set this user to the bl-content folder.

chown USER:USER /bl-content/

Regards

**Comment by dignajar** [comment]
Hi, it's works ?

**Comment by danielyf** [comment]
Oh, sorry.

Yes, It works flawlessly, thank you!
