### ISSUE TITLE
Javascript in page and article

### ISSUE THREAD

**Issue by spookssi** [dignajar/bludit#248]
Hi, im using your CMS since two weeks now and i dont understand how to add some javascript on my pages ( pages created using the administration).

I using some html5 canvas in my work and i want to display some canvas with paperJs script in a page.

How can i do that without breaking the cms lol ?
Can i directly add the html code with `<script src="..."> ... </script> and <canvas id=... >` etc... ?

Thx you .

**Comment by dignajar** [comment]
Hi, what HTML editor do you used and version of Bludit ?

**Comment by acrox999** [comment]
Markdown should have no problems with HTML and JavaScript.

**Comment by spookssi** [comment]
I'm using Atom and last stable build of Bludit. I will test in the markdown editor of bludit.

**Comment by zh-wowtv** [comment]
I added something in my post:

```
    <p>This is a demo</p>
    <script>
		alert('hi');
    </script>
```

But only **alert('hi')** is shown as text.

**Comment by zh-wowtv** [comment]
Fixed. Because of the space at the beginning or end of each line.
