### ISSUE TITLE
Notify when a new version is released on Dashboard

### ISSUE THREAD

**Issue by dignajar** [dignajar/bludit#249]
Notify when a new version is released on Dashboard.

**Comment by anaggh** [comment]
Great idea! This way we won't have to keep up with Bludit social media pages and can update immediately if there is any security updates!

**Comment by Sirjoseph94** [comment]
i would love if this feature is implemented

**Comment by dignajar** [comment]
This feature is implemented as a plugin on the next version of Bludit v2.0. Regards.
