### ISSUE TITLE
Feature Request: Link Error Codes to Help

### ISSUE THREAD

**Issue by billymail** [dignajar/bludit#260]
Dropped in folder, unzipped:
File .htaccess
Missing file, upload the file .htaccess (ERR_201)

PHP permissions
Writing test failure, check directory content permissions. (ERR_205)

It would be nice to link to instructions
(in first case, when I copied the unzipped files, the hidden file did not copy).

In the second step, I need to enable permissions on content folder.
(a link, a mention of the bl-content folder, a mention of required permissions)

**Comment by billymail** [comment]
After adding 775 to content (I didn't find an explanation for that), now I have:
PHP permissions
Writing test failure, check directory content permissions. (ERR_205)
No context for what directory.

**Comment by billymail** [comment]
Per this document, I had to try 777 on the bl-content folder.
https://docs.bludit.com/en/troubleshooting/writing-test-failure-err205

**Comment by clickwork-git** [comment]
Normally you have not to set permissions. What server environment do you use? Which hoster?

**Comment by billymail** [comment]
Self Hosted CentOS server.

**Comment by clickwork-git** [comment]
No clue of this environment. :-(

Perhaps somebody in the chat or the forum knows it.

**Comment by billymail** [comment]
Well, I got there using the permissions changes recommended in the documentation about error 205 - This issue is just to mention that a link to the documentation in en (referencing other lang links) might be helpful in the error message.

**Comment by dignajar** [comment]
Hi @billymail check the documentation to install on GNU/Linux Centos.
https://docs.bludit.com/en/getting-started/installation-on-gnu-linux#centos

The best practice is set the directory owner with the user who is running the webserver app. The permission 777 are hazardous.
