### ISSUE TITLE
adding class

### ISSUE THREAD

**Issue by iskono** [dignajar/bludit#266]
how to set class active for each page ?
my default theme has <li class active>
how to add it in this code 
				`<?php
				echo '<li><a href="'.$Site->homeLink().'">'.$Language->get('Home').'</a></li>';
				$parents = $pagesParents[NO_PARENT_CHAR];
				foreach($parents as $Parent) {
					echo '<li><a href="'.$Parent->permalink().'">'.$Parent->title().'</a></li>';
				}
				?>`
when i add the active class inside the li , all buttons becomes active 
any suggestions ?

**Comment by dignajar** [comment]
Hi, try make the question in the forum. https://forum.bludit.com
Regards
