### ISSUE TITLE
New language avaible

### ISSUE THREAD

**Issue by asbmails2** [dignajar/bludit#269]
Good night

I made a translate of Bludit to Portuguese. I'm new in gitHub and I don't know how I can send it to became part of the project.

[pt_BR.zip](https://github.com/dignajar/bludit/files/248069/pt_BR.zip)

I hope that is useful.

Thanks,
ASB

**Comment by dignajar** [comment]
Hi, thanks, here you have a guide to push content in the repository.

https://varlogdiego.com/post/how-to-contribute-to-a-github-project
