### ISSUE TITLE
Some language localization bugs in "log" theme

### ISSUE THREAD

**Issue by xm74** [dignajar/bludit#282]
Seems language localization doesn't works for post's data and next / previous page buttons.
See screenshots for details - http://imgur.com/a/vJHaR

**Comment by dignajar** [comment]
The date it's taken from the locale, you have set the locale correctly ?

And the prev and next page now is fixed.

**Comment by xm74** [comment]
About date. Just checked and you are right - locale for www user was wrong,
Thanks!

**Comment by xm74** [comment]
But may be will be better in future to take locale for date field from Bludit setting page "Language and timezone"? Because system locale may be different from site language and depends from system settings.

**Comment by dignajar** [comment]
When you change the language, the locale changes, or not ?

**Comment by xm74** [comment]
When I change language in Bludit admin page locale changes but data format don't
