### ISSUE TITLE
[Feature Request] Change limit of dashboard posts

### ISSUE THREAD

**Issue by anaggh** [dignajar/bludit#284]
By default Dashboard -> Manage posts,  returns 10 posts at a time. Where do I change this value to 100 or any other custom value? It would be nice if this value could be configured in Settings -> Advanced since we do not have a search function yet to find posts. We could use Ctrl+F on the browser as a temporary solution.

**Comment by dignajar** [comment]
Hi,
there is a lot of variable here, bl-kernel/boot/init.php, change this variable, POSTS_PER_PAGE_ADMIN

Regards

**Comment by anaggh** [comment]
Thanks! Just realised it's also mentioned on https://docs.bludit.com/en/developers/variables . I should RTFM more often! :laughing:
