### ISSUE TITLE
No image resize in "log" theme

### ISSUE THREAD

**Issue by xm74** [dignajar/bludit#287]
see screenshot http://imgur.com/jpV0zuG

**Comment by anaggh** [comment]
Adding the below css should fix it.
```
img{
	max-width: 100%;
}
```

**Comment by xm74** [comment]
Well, maybe you will make a patch?

**Comment by alexandreteles** [comment]
I've pushed a patch in the PR #331. Can you, please, give it a try and provide some feedback?

**Comment by xm74** [comment]
> I've pushed a patch in the PR #331. Can you, please, give it a try and provide some feedback?

Yes, it's works! Thank you!
