### ISSUE TITLE
Empty themes listing in preferences after upgrade 1.3 → 1.4

### ISSUE THREAD

**Issue by ParoTheParrot** [dignajar/bludit#293]
The themes are not listed any more. Any idea?

**Comment by dignajar** [comment]
Hi,
yes it's because of the compatible field on themes, I recently update the themes.

On the file metadata.json, you need to add the field "compatible" and add the version of Bludit.

**Comment by HoundSU** [comment]
Solution: All themes must have as @dignajar mentioned the Compatible line example:

`
Alexander K @HoundSU 11:05
{
"author": "n33co",
"email": "",
"website": "https://github.com/dignajar/bludit-themes",
"version": "1.1",
"releaseDate": "2016-01-21",
"license": "CCA 3.0",
**"compatible": "1.0,1.1,1.1.2,1.3,1.4",**
"notes": "This theme is based on Future Imperfect, all credits to the author n33co."
}`

Without that line no themes shall work.

**Comment by dignajar** [comment]
I made the updates on all themes from themes.bludit.com
