### ISSUE TITLE
SimpleMDE is buggy with mobile browser

### ISSUE THREAD

**Issue by Max-malRichtig** [dignajar/bludit#297]
I encountered some strange habits by the simpleMDE editor while trying to edit some posts on my mobile. When I erase some words, then type something different, then erase something again, everything that was erased previously comes back into existence.  

eg.: 

1. "My xde name is" -> erase and add something
2. "My name is max" -> then erase something
3. "My **xde** name is ma"

can anybody confirm this behaviour?

---

I use a CyanogenOS/Android phone with Firefox mobile browser - I also tested it with an other browser, which led to the same bahavior. I've first encountered this bug about 6 months ago, so I don't think it has something to do with the current versions of my mobile-software.

--

EDIT: I don't have these problems when using the basic bludit-markdown-editor, that shows up when deactivating SimpleMDE.

**Comment by acrox999** [comment]
Do you have this problem when using SimpleMDE outside of Bludit?

If so, you will have to report this to SimpleMDE instead of here.
