### ISSUE TITLE
Add Folder Permissions For Github Version [Feature Request]

### ISSUE THREAD

**Issue by syndicatefx** [dignajar/bludit#3]
For those of us downloading or cloning the Github version why not add proper folder permissions to mirror bludit.com's official download version. In **my personal experience** i have to manually change folder and subfolder permissions to access bludit-master on my localhost.

```
find path/to/bludit-master -type d -exec chmod 755 {} \;
```
For *content/* folder

```
chmod 777 content
```

**Comment by dignajar** [comment]
Hi, I documented this issues on this page. http://docs.bludit.com/en/getting-started/installation-on-gnu-linux

Thanks!
