### ISSUE TITLE
Problem upload files with uikit

### ISSUE THREAD

**Issue by DrXala** [dignajar/bludit#300]
I can't upload new pictures with uikit tool in new article page!
I can select and valide picture, i see progress bar but i have no picture. When I check uplaod directory, I have no files.

I tryed with firefox 48 and chrome 51. I use bludit in github version.

Thank you

**Comment by mohanzeal** [comment]
Hi DrXala,

I think you are missing the **tmp** folder in your **/bl-content** folder. Create a folder with **tmp** name in the **/bl-content** folder and try uploading an image. I had the same issue and this might resolve your problem also.

**Comment by DrXala** [comment]
Hi mohanzeal,

I have **tmp** directory in my **bl-content** directory. I have check directory permissions and they are good.

**Comment by DrXala** [comment]
Hi,

I have try on other web server machine and I have the same. 
I use apache2 for these two servers.

**Comment by dignajar** [comment]
Hi,
could you post your php_error.log ?
thanks

**Comment by DrXala** [comment]
Hi dignaja,

```
[Tue Jul 12 11:32:20.038222 2016] [:error] [pid 3670] [client 83.157.124.76:35844] PHP Fatal error:  Call to undefined function imagecreatefromjpeg() in /data1/www/www.clamifa.net/bludit/bl-kernel/helpers/image.class.php on line 85, referer: http://www.clamifa.net/bludit/admin/new-post
[Tue Jul 12 11:32:20.121399 2016] [:error] [pid 3670] [client 83.157.124.76:35844] (1.4)buildPage | Error occurred when trying build the page from file with key: bl-content/uploads/thumbnails/undefined, referer: http://www.clamifa.net/bludit/admin/new-post
```

**Comment by janxb** [comment]
Do you have the GD module for PHP installed?
If not, install the following packages for your OS (depending on your PHP version..):
``
php5-gd
php7.0-gd
``

**Comment by DrXala** [comment]
Ok it's work fine after install `php5-gd` and restart apache2!
Thank you @janxb
