### ISSUE TITLE
Putting a colon on the title leads to friendly URL of /posts/empty

### ISSUE THREAD

**Issue by alfmel** [dignajar/bludit#302]
Whenever you put a colon in the title, the friendly URL becomes /posts/empty rather than having the title of the post. It makes me wonder: if you create two pages with that tile, will the second override the first?

**Comment by janxb** [comment]
I can't reproduce this bug with the latest master. Please see the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/1172106/17128970/7b129c76-5310-11e6-8e6f-959159cca359.png)

**Comment by alexandreteles** [comment]
Can't reproduce.

**Comment by anaggh** [comment]
![capture](https://cloud.githubusercontent.com/assets/9278844/18197747/80383a02-7116-11e6-9e82-2c57001f3685.PNG)
---
![capture2](https://cloud.githubusercontent.com/assets/9278844/18197748/81292ae8-7116-11e6-9d7b-294e1e0b7463.PNG)

Why would you have a post title with a single character?

**Comment by acrox999** [comment]
@anaggh Has shown that it will not overwrite the previous ones. So I guess the issue is resolved.

However, you're probably wondering why symbols are not generated in the friendly URL.

**Comment by dignajar** [comment]
There are some character you can't have in the URI. And the colon are to define the port number.
