### ISSUE TITLE
File uploading

### ISSUE THREAD

**Issue by zh-wowtv** [dignajar/bludit#305]
This is the best markdown CMS I ever use. I'm wondering if it's possible to add upload function for audio, video or even other files like pdf. So that we can use the link in our post. Thanks.

**Comment by zh-wowtv** [comment]
If I want to contribute, where should I start?

**Comment by acrox999** [comment]
Fork it, and hack away. Although you might actually want to fork SimpleMDE instead. It is very extensible.

**Comment by dignajar** [comment]
Hi, sorry for my late answer, you can fork the repository as say acrox999, and if you have some question, check the forum https://forum.bludit.com and the Gitter Chat https://gitter.im/dignajar/bludit
