### ISSUE TITLE
How to set the width of image?

### ISSUE THREAD

**Issue by zh-wowtv** [dignajar/bludit#309]
How to set the width of image after I insert it into a post or page? Thanks

**Comment by abdtif** [comment]
u can use Editor like Ckeditor  to resize images 

https://plugins.bludit.com/

**Comment by clickwork-git** [comment]
Or define the size with CSS.

**Comment by zh-wowtv** [comment]
I know how to set the size in CSS. But I'm wondering if it's possible to add an option in editor. 

@abdtif I found Ckeditor is not a good choice because I can't use markdown syntax anymore.

Thanks anyway.

**Comment by acrox999** [comment]
You can define them in the img tag. They are in pixels.

    <img src="image.jpg" height="100" width="100">

It might actually be a good idea to add such an option to editors, however all editors used in Bludit are third parties.

**Comment by acrox999** [comment]
Apparently, you can also do this with some Markdown. I'm not sure about Bludit though.

http://stackoverflow.com/a/21242579
