### ISSUE TITLE
Note if theme or plugin is not (yet) compatible

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#318]
As extension to the compatibility field in metadata.json there could be perhaps a note in the backend if a theme or a plugin is not (yet) compatible to the installed version.

**Comment by acrox999** [comment]
There should be a notice at the theme listing. User should be allowed to enable them if they still want to use an incompatible theme.

**Comment by anaggh** [comment]
I think the incompatible theme/plugin should have a warning with a light red background color instead of hiding it completely. :D

"_This theme/plugin is incompatible with your Bludit version. Proceed at your own risk."_

**Comment by dignajar** [comment]
Implemented on the Github version!
