### ISSUE TITLE
Request for update page position menu directly in page list.

### ISSUE THREAD

**Issue by Fred89** [dignajar/bludit#32]
https://github.com/Fred89/bludit/commit/10af51bb2b940831d870b47043678bdcc3843b3b

Sorry Diego, i don't understand, i don't pull request directly in your depot :(

**Comment by dignajar** [comment]
mmm I don't know what is the error, can you show me the error ?

**Comment by Fred89** [comment]
I don't have error, normally the pull is default in your branch

**Comment by Fred89** [comment]
I deleted repo and notice a another pull with new fork
