### ISSUE TITLE
Specify image size in markdown

### ISSUE THREAD

**Issue by abagshaw** [dignajar/bludit#324]
Can the size (width or height or both) of an image be specified in the markdown?

I've tried what appears to be the most common format `![](img.jpg =200x100)` but that doesn't work (the image fails to render.

If this isn't implemented, would there be an easy way I could add it in? I've been exploring the code to see if there's any easy way I could add this functionality but I'm not exactly sure where the actual markdown -> html conversion happens for the image tags.

Thanks!

**Comment by dignajar** [comment]
Hi,
Bludit uses this library for parse Markdown, https://github.com/erusev/parsedown

And this extra, https://github.com/erusev/parsedown-extra

Do you know if there are a better library ? maybe this parsedown library is deprecated.

Thanks

**Comment by alexandreteles** [comment]
> @dignajar said:
> [...] Do you know if there are a better library ? [...]

I personally like https://github.com/thephpleague/commonmark very much, but it would break the Bludit's compatibility with PHP 5.3.

**Comment by alexandreteles** [comment]
> @abagshaw said:
> I've tried what appears to be the most common format `![](img.jpg =200x100)` but that doesn't work (the image fails to render.

If you really need something like that, you can always use pure HTML with your Markdown, it will work flawlessly. We can solve this problem without messing with parsedown itself with jQuery or CSS3 substring selectors. What I don't know is if we want a solution like that. Do we?

**Comment by alexandreteles** [comment]
@abagshaw I've pushed a plugin on the dignajar/bludit-plugins#79 PR to solve this little issue without messing with the markdown parsing code. Could you try it and see if it fit your needs?

**Comment by alexandreteles** [comment]
Plugin merged.
