### ISSUE TITLE
[Bug] Social Network Links not working

### ISSUE THREAD

**Issue by anaggh** [dignajar/bludit#330]
$Site->twitter(), $Site->facebook() and the rest are not returning correct links.

**Comment by alexandreteles** [comment]
@anaggh They are returning incorrect links ou no link at all? Can you provide some code examples of what are you doing?

**Comment by anaggh** [comment]
Oops! I tried to enter only the username (example_user) in /admin/settings-general and expected it to return the whole URL in the sidebar. It works fine if you enter the whole URL for example -> https://twitter.com/example_user

My bad, Closing the issue.
