### ISSUE TITLE
navigation is broken

### ISSUE THREAD

**Issue by turbopixel** [dignajar/bludit#338]
My navigation is broken. I have Version 1.4a "Spot". (Theme Journal, Clean, Clean Blog, ...)
 
**HTML Example**

`<ul>
 <li><a class="parent" href="/">Hauptseite</a></li>
 <li><a class="parent " href="/nico">Nico</a>
 <li><a class="parent " href="/projekte">Projekte</a>
 <ul class="children">
   <li class="child"><a class="" href="/projekte/robotstxt-viewer">robots.txt viewer</a></li>
  <li class="child"><a class=" active" href="/projekte/user-access-information-uai">User Access Information (UAI)</a></li>
 </ul>
 <li><a class="parent " href="/impressum">Impressum</a></li>
</ul>
`

There are no `</li>`-elements between the menu items.

**Comment by turbopixel** [comment]
solution:

./bl-plugins/pages/plugin.php - add to line 83:

`$html .= '</li>';`

**Comment by dignajar** [comment]
Fixed, https://github.com/dignajar/bludit/commit/26670ae9a8c4b953acc829bac8bc0d1aa7e464ae

thanks
