### ISSUE TITLE
Paginas en dos idiomas

### ISSUE THREAD

**Issue by Albertogon** [dignajar/bludit#340]
Hola
Estoy intentando poder tener las Paginas en dos idiomas y para ello básicamente he duplicado el titulo y el contenido y todos sus métodos para luego leer según mis necesidades unas u otras.
Me graba perfectamente en los txt la estructura nueva pero a la hora de cargar los dos contenidos se mezclan en el primero.
¿Puede ser por la forma en que lee el txt? Desde "Content:" hasta el final del txt?

Contenido del txt:
Title: test
Title_lang: test2
Content: text
Content_lang: texto2

![edit](https://cloud.githubusercontent.com/assets/2592221/18637763/d353b8c2-7e8d-11e6-92ad-b11e715b2175.JPG)

Muchas gracias.

**Comment by dignajar** [comment]
Hola,
proba guardar el field "Content_lang" antes de "Content:"

**Comment by dignajar** [comment]
El ultimo campo en el archivo debe ser "content:". Saludos
