### ISSUE TITLE
Notice when all pages are deleted

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#352]
When all pages are deleted the following notice is shown (backend and frontend):

> Notice: Undefined index: 3849abb4cb7abd24c2d8dac17b216f17 in /var/www/webxxx/html/xxx/bl-kernel/functions.php on line 240

**Comment by dignajar** [comment]
I fixed today, here https://github.com/dignajar/bludit/commit/114caa9b8c8ae47426c1a75afd7da9c3a5c28361
