### ISSUE TITLE
404 everywhere

### ISSUE THREAD

**Issue by Turqueso** [dignajar/bludit#356]
I'm trying to run it locally with MAMP on mac Sierra. After installing successfully it's redirected to the initial page but everything else (page, post, admin area) I get:

Not Found
The requested URL /indesol/post/first-post was not found on this server.

Anyone with a similar situation?

**Comment by anaggh** [comment]
How is it /indesol/post/first-post ? The directory path should be /bl-content/posts/first-post 
Also make sure .htaccess is present at root of the installation.

**Comment by Turqueso** [comment]
@anaggh changed from MAMP to XAMPP and, after some struggle, started working. Thanks for your help.
