### ISSUE TITLE
Feature request: set a custom page as home

### ISSUE THREAD

**Issue by krasimir-georgiev** [dignajar/bludit#358]
Do you think you can add an option to use a page as home landing page?

Then the blog overview page should be moved to the menu with a custom url /blog to see all teaser blogs

**Comment by turbopixel** [comment]
I like this and need it for my website too

**Comment by acrox999** [comment]
It has always been there. Go to Advanced setting and change your Default
home page.

**Comment by krasimir-georgiev** [comment]
Yes sorry my bad.
