### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Maik-Thiele** [dignajar/bludit#368]
With  dbaf520 I got error 500 because of the htaccess.
After deleting the installer stops. Any idea?

**Comment by clickwork-git** [comment]
Only when installing in Ukrainian?

**Comment by Yoneo** [comment]
For me it has helped to remove the #-Symbol before the Line with the RewriteBase.

# Base directory
(#) RewriteBase /

**Comment by dignajar** [comment]
@Yoneo which web server are you using?
When you install Bludit for the first time, try to create the file .htaccess with the correct value for `RewriteBase`.

**Comment by Yoneo** [comment]
> @Yoneo which web server are you using?

I use a Linux Server (hosted at [uberspace.de](https://uberspace.de)). The Install-Page wasn´t reachable before I have removed the #-Character.
