### ISSUE TITLE
Minor issue: Browser spellcheck doesn't work with add new post text box

### ISSUE THREAD

**Issue by ThePrudentNinja** [dignajar/bludit#369]
To put it simply, the browser spellcheck in Google Chrome doesn't work with the text input field when adding a new post. I can't seem to find a way around it so wanting to alert the devs in case this was unknown or known with a workaround.

Latest Bludit and latest Google Chrome on Linux. The title field works with spellcheck but not the main text field for the post.

**Comment by clickwork-git** [comment]
Which editor do you use?

**Comment by ThePrudentNinja** [comment]
SimpleMDE from the looks of it.

**Comment by clickwork-git** [comment]
I checked it. It's not a problem of Bludit. SimpleMDE is not capable to use the spellchecker. You can try the demo at

https://simplemde.com

**Comment by ThePrudentNinja** [comment]
Hmm, so could this be fixed or would a different editor be needed? If so, any suggestions? I'm new to Bludit, but love how fast it is.

**Comment by clickwork-git** [comment]
SimpleMDE has its own spellchecker. I will try to install/activate it.

**Comment by clickwork-git** [comment]
Okay, you can activate the spellchecker by editing the file plugin.php in /bl-plugins/simplemde.

Set "spellChecker: true," in line 126 (instead of "spellChecker: false,").

**Comment by ThePrudentNinja** [comment]
Works for me and thus essentially closes this issue. Having this change in the distributed Bludit would possibly be a good idea.

**Comment by clickwork-git** [comment]
The problem is, as far as I understand it, that the spellchecker is only for English. But perhaps the on/off option can be added to the plugin settings.

**Comment by ThePrudentNinja** [comment]
Didn't realize that, yes an option in the plugin would be suitable.
