### ISSUE TITLE
Bug with Page + plugin use Hook pageEnd

### ISSUE THREAD

**Issue by Fred89** [dignajar/bludit#37]
Diego, with your new push a bug is arrived:
```
Warning: implode() [function.implode]: Invalid arguments passed in /home/u680092465/public_html/kernel/page.class.php on line 68
```
If a plugin use Hook pageEnd.

For fix this, i edit the class.page.php line 58 and i replace this
``` php
if($returnsArray) {
```
by
``` php
if(!is_array($returnsArray)) {
```

Same problem and fix in Warning: implode(): Invalid arguments passed in post.class.php on line 130

**Comment by dignajar** [comment]
I made changes for store the tags, you made a clean installation ?

**Comment by Fred89** [comment]
In a clean install, is work great.

**Comment by dignajar** [comment]
I made the changes on the function generateTags.
