### ISSUE TITLE
API keys are getting leaked and Ping Bludit.com should be off by default.

### ISSUE THREAD

**Issue by anaggh** [dignajar/bludit#373]
https://api.bludit.com/

*Removed Image*

I think Ping Bludit.com should be off by default and should be done only when the user has agreed to share his/her posts and pages with Bludit server.

It is very misleading and equivalent to data-theft/backdoor. Activate the API plugin and the private key is sent to bludit server by default. All the posts/pages are leaked without the user even knowing.

**Comment by Turqueso** [comment]
I don't have the plugin activated and my site is showing there

**Comment by clickwork-git** [comment]
It seems that the installations have activated the plugin. None of my installations is showing.

But perhaps the plugin should not be part of the distribution.

@Turqueso Are you shure that the plugin is disbled?

**Comment by Turqueso** [comment]
@clickwork-git positive, it is not active

**Comment by clickwork-git** [comment]
I tried with a installation for test purposes. The problem seems to be the following: If the API was activated and then deactivated the entry is still there.

**Comment by anaggh** [comment]
The API plugin is very useful as you can see here - https://docs.bludit.com/en/misc/embed-bludit-in-my-website but the problem is with private websites. Since Ping Bludit.com is on by default, it automatically sends the key to the server as soon as the plugin is activated. If you deactivate the plugin and reactivate it to get a new key, again it pings bludit.com without the user's permission since it is on by default.

**Comment by dignajar** [comment]
Sorry for this, I will disable the ping to Bludit.com by default.

**Comment by dignajar** [comment]
@anaggh could you edit the issues, and delete the image, thanks.

**Comment by dignajar** [comment]
For the moment, the API plugin just read from the database, but I would like to make a bigger API, with some feature to ADD / EDIT / DELETE posts/pages from outside the CMS.

**Comment by dignajar** [comment]
I'm working on the API plugin, to improve it, I will change some parts of the URL, to make it more a API REST..

**Comment by dignajar** [comment]
Here is the documentation of the new API https://docs.bludit.com/en/api/introduction

This API is not yet finished, I listen to new ideas, features improves.

**Comment by dignajar** [comment]
I close the ticket. Please take a look at the new beta version to check possibles fixes for this issue, https://github.com/dignajar/bludit/releases/tag/2.0-beta7
Feel free to open a new ticket if the problem persists with the latest version.
