### ISSUE TITLE
Features under "General"

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#376]
The features under "General" should not to be "hidden" ("Images", "Advanced"). Some user cannot find them.

There is a mockup for a possible solution by @ThaMattie.

![2016-11-28 19_25_51-untitled-1](https://cloud.githubusercontent.com/assets/14312561/20846630/dfe3df6e-b8ca-11e6-9993-47f10eed385d.png)

**Comment by Turqueso** [comment]
other idea
![image](https://cloud.githubusercontent.com/assets/4932347/20846938/29fe383e-b889-11e6-96f3-ee59dddcf660.png)

**Comment by dignajar** [comment]
Done! check the changes on Github, still under beta, but you can test it.

**Comment by ThaMattie** [comment]
Much more clear, thanks!

**Comment by ADTC** [comment]
I adjusted the widths to be 70/30 instead of the original 80/20 which made the three tabs show up together. (I just did this in my personal Bludit installation.)
