### ISSUE TITLE
Prettier commit messages

### ISSUE THREAD

**Issue by turbopixel** [dignajar/bludit#378]
Hey,
can you pls make better commit messages, that contains more informations about a change?

I don't like this:
![519bfa240d6b44d58a0411af44166ae4](https://cloud.githubusercontent.com/assets/15839724/20899636/75ef2e3e-bb2b-11e6-806e-19caa7333f52.png)

**Comment by dignajar** [comment]
Could you please pay me for my work ? thanks

**Comment by clickwork-git** [comment]
Diegos code is well documented. Therefore it's additional work.

It's something else if somebody contributes to another repository.
