### ISSUE TITLE
Post titles in url + tag system

### ISSUE THREAD

**Issue by patrickbolle** [dignajar/bludit#38]
Hi Diego, loving bludit so far. Have it implemented on my site here - http://patrickbollenbach.me/blog/post/empty

As you can see in the url, the post title is labeled as "empty", the next post is called "empty_0" and so on. Not sure if you have this on your todo list, just thought I'd let you know!

Also, I don't seem to have any way of tagging my posts. Am I missing something here or is that just not fully implemented yet?

Cheers Diego, I will be having a look at the source code tomorrow afternoon to see if I can push anything useful.

**Comment by dignajar** [comment]
Hi Patrick,
the empty URI is because you have an empty post title, you can change the
slug editing the post, on advanced options.
What version of Bludit are you using ? v0.1 or from github ?

Regards
Diego

**Comment by patrickbolle** [comment]
My post title doesn't seem to be empty though? It is "what I am listening to (part1) ".
I am using the latest version from the bludit website, not from github.

It seems as if my advanced options button just saves the post and refreshes the page, doesn't bring up any actual advanced options.

If I were to upgrade, would I lose all my current settings and posts?

Cheers Diego, thanks for your work

Sent from my BlackBerry 10 smartphone on the Bell network.
From: Diego Najar
Sent: Sunday, September 20, 2015 11:43
To: dignajar/bludit
Reply To: dignajar/bludit
Cc: Patrick Bollenbach
Subject: Re: [bludit] Post titles in url + tag system (#38)


Hi Patrick,
the empty URI is because you have an empty post title, you can change the
slug editing the post, on advanced options.
What version of Bludit are you using ? v0.1 or from github ?

Regards
Diego

On Sat, Sep 19, 2015 at 10:46 PM, Patrick Bollenbach <
notifications@github.com> wrote:

> Hi Diego, loving bludit so far. Have it implemented on my site here -
> http://patrickbollenbach.me/blog/post/empty
>
> As you can see in the url, the post title is labeled as "empty", the next
> post is called "empty_0" and so on. Not sure if you have this on your todo
> list, just thought I'd let you know!
>
> Also, I don't seem to have any way of tagging my posts. Am I missing
> something here or is that just not fully implemented yet?
>
> Cheers Diego, I will be having a look at the source code tomorrow
> afternoon to see if I can push anything useful.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/dignajar/bludit/issues/38>.
>

-
Reply to this email directly or view it on GitHub<https://github.com/dignajar/bludit/issues/38#issuecomment-141797411>.

DISCLAIMER: This E-mail and any attachments contain privileged and confidential information intended only for the individual or entity named in the message. If the reader of this message is not the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is prohibited. Conestoga College accepts no liability for any loss or damages, however incurred, resulting from the use of this e-mail or its attachments. Conestoga College does not warrant the integrity of this e-mail, nor that it is free of errors, viruses, interception or interference.
DISCLAIMER: This E-mail and any attachments contain privileged and confidential information intended only for the individual or entity named in the message. If the reader of this message is not the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is prohibited. Conestoga College accepts no liability for any loss or damages, however incurred, resulting from the use of this e-mail or its attachments. Conestoga College does not warrant the integrity of this e-mail, nor that it is free of errors, viruses, interception or interference.

**Comment by dignajar** [comment]
Yes, it's a bug on permissions files, Try download the theme for admin area
from Github, https://github.com/dignajar/bludit/tree/master/admin/themes
and replace, or if you have access to the filesystem and some CLI you can
execute this:

find . -type d -exec chmod 755 {} \;

find . -type f -exec chmod 644 {} \;

**Comment by patrickbolle** [comment]
Got it!!! Cheers Diego. Really appreciate the help.

Sent from my BlackBerry 10 smartphone on the Bell network.
From: Diego Najar
Sent: Sunday, September 20, 2015 11:52
To: dignajar/bludit
Reply To: dignajar/bludit
Cc: Patrick Bollenbach
Subject: Re: [bludit] Post titles in url + tag system (#38)


Yes, it's a bug on permissions files, Try download the theme for admin area
from Github, https://github.com/dignajar/bludit/tree/master/admin/themes
and replace, or if you have access to the filesystem and some CLI you can
execute this:

find . -type d -exec chmod 755 {} \;

find . -type f -exec chmod 644 {} \;

On Sun, Sep 20, 2015 at 12:47 PM, Patrick Bollenbach <
notifications@github.com> wrote:

> My post title doesn't seem to be empty though? It is "what I am listening
> to (part1) ".
> I am using the latest version from the bludit website, not from github.
>
> It seems as if my advanced options button just saves the post and
> refreshes the page, doesn't bring up any actual advanced options.
>
> If I were to upgrade, would I lose all my current settings and posts?
>
> Cheers Diego, thanks for your work
>
> Sent from my BlackBerry 10 smartphone on the Bell network.
> From: Diego Najar
> Sent: Sunday, September 20, 2015 11:43
> To: dignajar/bludit
> Reply To: dignajar/bludit
> Cc: Patrick Bollenbach
> Subject: Re: [bludit] Post titles in url + tag system (#38)
>
>
> Hi Patrick,
> the empty URI is because you have an empty post title, you can change the
> slug editing the post, on advanced options.
> What version of Bludit are you using ? v0.1 or from github ?
>
> Regards
> Diego
>
> On Sat, Sep 19, 2015 at 10:46 PM, Patrick Bollenbach <
> notifications@github.com> wrote:
>
> > Hi Diego, loving bludit so far. Have it implemented on my site here -
> > http://patrickbollenbach.me/blog/post/empty
> >
> > As you can see in the url, the post title is labeled as "empty", the next
> > post is called "empty_0" and so on. Not sure if you have this on your
> todo
> > list, just thought I'd let you know!
> >
> > Also, I don't seem to have any way of tagging my posts. Am I missing
> > something here or is that just not fully implemented yet?
> >
> > Cheers Diego, I will be having a look at the source code tomorrow
> > afternoon to see if I can push anything useful.
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dignajar/bludit/issues/38>.
> >
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/dignajar/bludit/issues/38#issuecomment-141797411>.
>
> DISCLAIMER: This E-mail and any attachments contain privileged and
> confidential information intended only for the individual or entity named
> in the message. If the reader of this message is not the intended
> recipient, you are hereby notified that any review, dissemination,
> distribution or copying of this communication is prohibited. Conestoga
> College accepts no liability for any loss or damages, however incurred,
> resulting from the use of this e-mail or its attachments. Conestoga College
> does not warrant the integrity of this e-mail, nor that it is free of
> errors, viruses, interception or interference.
> DISCLAIMER: This E-mail and any attachments contain privileged and
> confidential information intended only for the individual or entity named
> in the message. If the reader of this message is not the intended
> recipient, you are hereby notified that any review, dissemination,
> distribution or copying of this communication is prohibited. Conestoga
> College accepts no liability for any loss or damages, however incurred,
> resulting from the use of this e-mail or its attachments. Conestoga College
> does not warrant the integrity of this e-mail, nor that it is free of
> errors, viruses, interception or interference.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/dignajar/bludit/issues/38#issuecomment-141797601>.
>

-
Reply to this email directly or view it on GitHub<https://github.com/dignajar/bludit/issues/38#issuecomment-141797924>.

DISCLAIMER: This E-mail and any attachments contain privileged and confidential information intended only for the individual or entity named in the message. If the reader of this message is not the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is prohibited. Conestoga College accepts no liability for any loss or damages, however incurred, resulting from the use of this e-mail or its attachments. Conestoga College does not warrant the integrity of this e-mail, nor that it is free of errors, viruses, interception or interference.
DISCLAIMER: This E-mail and any attachments contain privileged and confidential information intended only for the individual or entity named in the message. If the reader of this message is not the intended recipient, you are hereby notified that any review, dissemination, distribution or copying of this communication is prohibited. Conestoga College accepts no liability for any loss or damages, however incurred, resulting from the use of this e-mail or its attachments. Conestoga College does not warrant the integrity of this e-mail, nor that it is free of errors, viruses, interception or interference.
