### ISSUE TITLE
missing favicon creates an 500 error?

### ISSUE THREAD

**Issue by Turqueso** [dignajar/bludit#389]
I'm using 1.6-beta. I logged in and got a 500 error, checked the error log and found:
```
[23-Jan-2017 07:14:16 America] (1.6-beta)buildPage | Error occurred when trying build the page from file with key: bl-themes/klean/img/favicon.png
[23-Jan-2017 07:23:00 America] (1.6-beta)buildPage | Error occurred when trying build the page from file with key: favicon.ico
```
Uploaded the icons and the error is gone now. The error logs the same error a number of times in the past (didn't realise the theme didn't hace favicon image), not sure if it's actually related.

**UPDATE**
Nope, got the error again. Could it be my shared hosting? I reloaded a minute later and error was gone. error_log says nothing this time.

**Comment by acrox999** [comment]
I never had this problem. In fact, my theme asks for a favicon but I still don't have any favicon yet it worked fine. Check with your host. Perhaps there's something in their configuration that made it happen.

**Comment by dignajar** [comment]
I close the ticket. Please take a look at the new beta version to check possibles fixes for this issue, https://github.com/dignajar/bludit/releases/tag/2.0-beta7
Feel free to open a new ticket if the problem persists with the latest version.
