### ISSUE TITLE
bl-content as symlink

### ISSUE THREAD

**Issue by ADTC** [dignajar/bludit#396]
I have two sites that are sharing the same site code (via Git). But since the bl-content folder is dynamically generated, I am not committing anything from it in the Git repo. So, to share the same bl-content folder, I made a symlink in site 2 to the actual directory in site 1. So it's site2/bl-content -> site1/bl-content.

The problem is, the posts or pages don't show on site 1, although the rest of the blog works fine. I can log in with the same username and password in admin area, and it tells me there are x number of posts, but when I look at the posts lists, it's blank. If I try a known post url from site 2 and change it to site 1, I get this error:

> Notice: Undefined offset: 0 in /site2/blog/bl-kernel/url.class.php on line 118

In Apache2 error log, I get some errors like:

>[:error] .. (1.5.2)buildPost | Error occurred when trying build the post from file with key: _url of blog post goes here_

I tried to check if this is a permission problem (that the site2 is unable to write or something), but I don't seem to find anything amiss.

The blog posts work fine in site1 where the bl-content is an actual directory, but don't work in site2 where the bl-content is a symlink to the site1's bl-content directory. How can I fix this problem while keeping the symlink arrangement?

**Comment by dignajar** [comment]
Hi,
try to change this line for FALSE.

https://github.com/dignajar/bludit/blob/master/bl-kernel/boot/init.php#L60

Regards

**Comment by ADTC** [comment]
Oh wow, I knew had something to do with symlinks. May I know why it's default to TRUE and **what are "symlink attacks"**?

BTW, That works. Thanks! 😄

**Comment by dignajar** [comment]
Check this example, is more easy to explain http://php.net/manual/en/security.filesystem.php
