### ISSUE TITLE
Small Issues

### ISSUE THREAD

**Issue by 1Seann** [dignajar/bludit#4]
#### 1. Posts
Once a new post has been created the title is linked incorrectly. Trying to take you to **//post/first-post** for example: 
```<a class="ptitle" href="//post/first-post">First post</a>```

#### 2. Language Files
The current English language file is named **en_EN.json**, to use the correct locale it should become either **en_US.json** or **en_GB.json**

#### 3. Regional > Locale
Currently the setting is **en_EN** [Facebook debugger](https://developers.facebook.com/tools/debug/og/object/) throws an error while trying to define it as it isn't a correct Locale option, I recommend it gets changed to a default state of **en_US** or **en_GB**.

**Comment by dignajar** [comment]
Fixed! thanks for reports the bugs.
