### ISSUE TITLE
How to add permalink and page identifier for Disqus?

### ISSUE THREAD

**Issue by ADTC** [dignajar/bludit#409]
Disqus highly recommends that you use permalink URL and page identifier to avoid problems with Disqus. These problems include split threads, missing comments and dirty URLs shown in email notifications. Here is [the official article from Disqus](https://help.disqus.com/customer/en/portal/articles/2158629) detailing this.

I noticed that Bludit's Disqus plugin doesn't add page identifier or permalink. May I know what's the easiest way to add these? I can PR the change once I successfully add these, but a little guidance will be helpful. Also, does Bludit generate a unique identifier number for each post or page? This is different from the permalink because if the title changes, the permalink changes but the unique identifier number remains the same. This is very helpful in redirecting old permalinks and also in making sure Disqus loads the correct set of comments even if the title has changed.

PS/Sidenote: Another thing I noticed is that the Disqus plugin **by default** enables the commenting system in the blog home page but disables it in the posts and pages. It doesn't make sense, as the posts and pages (or at least the posts) is where the commenting system is really needed.

**Comment by ADTC** [comment]
@dignajar I've been browsing through the post data, and looks like the posts don't have any unique fixed identifier that's already implemented. All the information currently stored on a post could be changed.

How do you recommend generating a unique identifier for a post or page? Would `uniqid()` or `random_bytes()` suffice?

**Comment by ADTC** [comment]
Successfully did this in my Bludit install. Will find some time to PR this if you're interested.

**Comment by dignajar** [comment]
Implemented.
