### ISSUE TITLE
Avatar profil upload failed

### ISSUE THREAD

**Issue by Fred89** [dignajar/bludit#411]
In admin, the upload avatar and save profil get a logout without save picture.
Try in the last github version (1.6)

**Comment by dignajar** [comment]
Hi Fred, I will try it.. I need to finished some stuff then I going to make all the tests.

**Comment by acrox999** [comment]
It seems like this issue is fixed now. Working fine on my end on the latest commit.

**Comment by dignajar** [comment]
Check the latest code on github, thanks
