### ISSUE TITLE
Fatal error in Plugin (googletools)

### ISSUE THREAD

**Issue by MegaBedder** [dignajar/bludit#412]
Path: bludit / bl-plugins / googletools / plugin.php [# L45](https://github.com/dignajar/bludit/blame/master/bl-plugins/googletools/plugin.php#L45)

**Message**:
> **Fatal error**: Can't use method return value in write context in /app-root/bl-plugins/googletools/plugin.php on line **45**

**Fix**:
```
		$site_verification = $this->getDbField('google-site-verification');
		if((!empty($site_verification)) && ($Url->whereAmI()=='home')) {

```

@0679a48823e2130d1ed807c212abf11f44a38527

**Comment by Turqueso** [comment]
@MegaBedder can you elaborate how you find this error? I want to try to replicate it

**Comment by dignajar** [comment]
Fixed. https://github.com/dignajar/bludit/blob/master/bl-plugins/googletools/plugin.php
