### ISSUE TITLE
Replace "Empty title" with a unique ID

### ISSUE THREAD

**Issue by acrox999** [dignajar/bludit#416]
I've been watching @ADTC's issue and PR to generate a (true) unique ID so that Disqus will work properly.

One thing that came to my mind is that it should also be used to generate the title of a post or a page using the unique ID if the user leave the title field empty instead of giving it "Empty title". This will also help avoid "/post/empty" friendly URL.

Should be great for turning Bludit into a microblog should the user desire so.

**Comment by acrox999** [comment]
I actually did this already but I'm not sure if it matters at all for a general use of Bludit (I'm using Bludit to start my own microblog), but anyway I guess I'll put it on hold first.

**Comment by acrox999** [comment]
By default they'll be "empty", "empty-0", "empty-1", "empty-2", ..., and so
on.

What I did for my "microblog" is that I changed the behaviour to both the
title and slug (URL) to the UUID should it be left empty. I'm thinking of
using truncated post body instead for the sake of SEO but maybe later.
That's not my priority.

Plus, Bludit is going to get a rework/refactor for 2.0 anyway so I might
want to hold off anymore changes for my own sake. Lol

**Comment by ADTC** [comment]
I like your idea of using a truncated post body, and I think that would be greatly beneficial over a uuid slug for SEO. Perhaps the first 10 words or so (configurable) of the post body can be used as a slug when there's no title.

Perhaps even there could be a "microblog" feature mode in Bludit 2.0 which when enabled would totally optimize Bludit for microblogging at the switch of a toggle.

**Comment by dignajar** [comment]
Hi, this features is implemented on the next version of Bludit v2.0, you can test it the alpha version.

https://github.com/dignajar/bludit/releases/tag/2.0-alpha3

Thanks for reports the bugs!

**Comment by dignajar** [comment]
About the default text for empty titles, I'm not sure to put the ID on the title, is not look nice... maybe get some words from the page body as say @ADTC.

I create an issues for it, to not forget, https://github.com/dignajar/bludit/issues/451

**Comment by acrox999** [comment]
I tried my best. It's been very long overdue. Please have a look.

Closing this in favor of #451 .
