### ISSUE TITLE
I have this error

### ISSUE THREAD

**Issue by Dipchikov** [dignajar/bludit#423]
Warning: Missing argument 4 for buildPostsForPage(), called in /home/u899309222/public_html/bl-kernel/boot/rules/70.posts.php on line 66 and defined in /home/u899309222/public_html/bl-kernel/functions.php on line 95

Notice: Undefined variable: key in /home/u899309222/public_html/bl-kernel/functions.php on line 105

**Comment by Turqueso** [comment]
Is this a custom theme? did you modify any bludit files?

**Comment by dignajar** [comment]
I think you are using the code from github?

**Comment by Dipchikov** [comment]
Yes I use  code from github.

**Comment by dignajar** [comment]
Can you try the lastest code ? I release a beta yesterday, https://github.com/dignajar/bludit/releases/tag/1.6-beta1

**Comment by Dipchikov** [comment]
Last 1.6-beta1 work normal.
