### ISSUE TITLE
1.6-BETA2: undefined index: uuid in dbpost.class.php

### ISSUE THREAD

**Issue by xm74** [dignajar/bludit#430]
When I made any edition in existing post and than save it for a first time I get this error on screen. 

> **Notice:** Undefined index: uuid in **/usr/local/www/kostikov.co/bl-kernel/dbpost.class.php** in **215**

Any other editions of a same post after goes without error. This happens for first edition of any existing post.

**Comment by acrox999** [comment]
Ah, this is probably because it was meant to keep the existing UUID but
didn't check if the UUID field is empty (on already existing post) or not
and to generate one or not.

**Comment by dignajar** [comment]
I going to add to the function updateBludit to generate the uuid for missing posts and pages.

**Comment by dignajar** [comment]
Fixed
