### ISSUE TITLE
$Language->get() uses the Text String not Variable name

### ISSUE THREAD

**Issue by jradxl** [dignajar/bludit#431]
Sorry if I'm wrong, but I'm not a PHP guru, and this looks odd to me.

Looking at Plugin "latest_posts"

en_US.json has
"amount-of-posts": "Amount of posts"

es_ES.json has
"amount-of-posts": "Cantidad de entradas"

But plugin.php has
$html .= '<label>'.$Language->get('Amount of posts').'</label>';

Whereas, using the variable name would seem more logical to me
$html .= '<label>'.$Language->get('amount-of-posts').'</label>';

**Comment by taktojest** [comment]
you're right. The second option is more flexible as you can use translation depends on your language settings. But the first one will works as well :) althought it will only returns "Amount of posts" string. Method get($key) is checking if given $key will be found in dbjson and if not it returns directly the key

**Comment by dignajar** [comment]
Hi,
the method get() convert the string to the key, and the dictionary file only has the key.

https://github.com/dignajar/bludit/blob/master/bl-kernel/dblanguage.class.php#L42-L54

**Comment by taktojest** [comment]
True :) I should check the code first, but still if the converted string is not found the string itself will be return.

**Comment by dignajar** [comment]
Yes, returns the string to keep some text on the UI, for example, if you change to Spanish and the dictionary is not updated is going to return an empty string so I prefer to return the string at least in English.

**Comment by taktojest** [comment]
Yes it is a good practice
