### ISSUE TITLE
Files path and embedd Twitter post issue

### ISSUE THREAD

**Issue by Hubenok** [dignajar/bludit#441]
Hi,
I noticed issue with embedded posts from twitter and files like images. 

For example here is twitter code

```
<blockquote class="twitter-tweet" data-lang="pl"><p lang="en" dir="ltr">Bludit is international <a href="https://twitter.com/hashtag/Qatar?src=hash">#Qatar</a> <a href="https://twitter.com/hashtag/Doha?src=hash">#Doha</a> <a href="https://t.co/xktofW1dEe">pic.twitter.com/xktofW1dEe</a></p>&mdash; Bludit (@bludit) <a href="https://twitter.com/bludit/status/706684712094453760">7 March 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

Here code transformed by bludit  - the last line was changed into

`<script async src="/bl-content/uploads///platform.twitter.com/widgets.js" charset="utf-8"></script>`

Similar if you add image
`<img src="gfx/image.jpg" alt="">`

Bludit will change it into
`<img src="/bl-content/uploads/gfx/image.jpg" alt="">`

**Comment by dignajar** [comment]
Hi,
yes is a little bug and regex.

I use this approach to insert the images in the editor and then parse the code, with this way the user don't need to put the full URL of the image.
https://docs.bludit.com/en/content/how-to-insert-an-image

Some recommendations?

**Comment by dignajar** [comment]
This feature was implemented on the latest beta version, please take a look https://github.com/dignajar/bludit/releases/tag/2.0-beta7
Feel free to open a new ticket if you need it.
