### ISSUE TITLE
Creating a directory with same name as a page makes that page inaccessible

### ISSUE THREAD

**Issue by haselkern** [dignajar/bludit#442]
Steps to reproduce / description of the problem:

1. Create a page `deadpage` from the bludit admin panel. Make sure the friendly URL is `deadpage ` too
2. The page gets recognized by bludit, as expected.
3. In your root directory, create a new folder `deadpage`.
4. deadpage still shows up as a page, but clicking it results in a `The page has not been found` error. This makes sense though, as placing an `index.php` with some content in the folder `deadpage` fixes this error and shows the `index.php`
5. Delete the folder `deadpage`
6. Trying to open `deadpage` now results in a `The page has not been found` error, altough you would expect it to show the page we saw in step 2 again.

Deleting and recreating the page `deadpage` doesn't solve the error. After deleting it, I even used `find` to look for remains of some file with `deadpage` in its name, but couldn't find anything. I also used `grep` to look through the file contents, but couldn't find `deadpage` anywhere either.

This effectively makes the friendly URL `deadpage` unusable.

I observed this behavior on Windows 10 with XAMPP and on a bplaced server ([phpinfo](http://phpinfo.bplaced.net/)).

**Comment by clickwork-git** [comment]
Have you cleared all caches (browser, server)?

**Comment by haselkern** [comment]
Well, that's an easy fix, thanks!
