### ISSUE TITLE
Theme::css('style.css') outputs HTTP instead of HTTPS

### ISSUE THREAD

**Issue by Torsten-K** [dignajar/bludit#443]
I found out that the following code outputs http:// etc., even if the website runs on https:
`Theme::css('style.css');`
The result is like: `<link rel="stylesheet" type="text/css" href="http://www.example.com/bludit/bl-themes/example/css/style.css">`

This code only outputs a relative path, so that there are no problems with the protocol:
`<link rel="stylesheet" href="<?php echo HTML_PATH_THEME_CSS ?>style.css">]`
The result is like: `<link rel="stylesheet" href="/bludit/bl-themes/example/css/style.css">`

**Comment by dignajar** [comment]
Hi, sorry for my late answer, I made some changes and research about this, and the best way to the theme has absolutes URLs, so the function return now the absolute URL and the protocol depends on the configuration of the user on Settings->Advanced->Site URL.

https://github.com/dignajar/bludit/blob/bluditv2/bl-kernel/helpers/theme.class.php#L98-L110

**Comment by dignajar** [comment]
This feature was implemented on the latest beta version, please take a look https://github.com/dignajar/bludit/releases/tag/2.0-beta7
Feel free to open a new ticket if you need it.
