### ISSUE TITLE
Fatal error in admin controller (settings-regional)

### ISSUE THREAD

**Issue by MegaBedder** [dignajar/bludit#447]
**Error message**:
> **URL**: https://localhost/admin/settings-regional
> 
> **Notice**: Undefined variable: Syslog in **/bl-kernel/admin/controllers/settings-regional.php** on line **23**
> 
> **Fatal error**: Call to a member function add() on a non-object in **/bl-kernel/admin/controllers/settings-regional.php** on line **23**

**Steps to reproduce the error**:
1. Access the administration panel.
2. In the left column, _Adjust_ > _Language and time zone_
3. Press the '_Save_' button
4. Error found

**About the version used**:

Name | Value
-- | --
Bludit version | 2.0
Bludit codename | Next
Bludit build | 20171010

**Comment by dignajar** [comment]
Fixed, thanks !

**Comment by dignajar** [comment]
I close the ticket. Please take a look at the new beta version to check possibles fixes for this issue, https://github.com/dignajar/bludit/releases/tag/2.0-beta7
Feel free to open a new ticket if the problem persists with the latest version.
