### ISSUE TITLE
Feature request: produce 404 for non existent tags

### ISSUE THREAD

**Issue by xm74** [dignajar/bludit#449]
I found that index.php produces 200s answers instead 404s for non existent (deleted) tags.

```
root@beta:~ # curl -I https://kostikov.co/tag/dasdsd
HTTP/2 200
server: h2o/2.2.2
date: Sun, 23 Jul 2017 14:39:30 GMT
x-powered-by: PHP/7.1.7
set-cookie: Bludit-KEY=65878e6d0280defeafbc7fb36c876abf; path=/; HttpOnly
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-type: text/html; charset=UTF-8
```

I believe 404s will be more correct answer in this case.

**Comment by dignajar** [comment]
Hi, yes you are right, thanks!

**Comment by dignajar** [comment]
Fixed for the next version. https://github.com/dignajar/bludit/releases/tag/2.0-alpha3

**Comment by dignajar** [comment]
This feature was implemented on the latest beta version, please take a look https://github.com/dignajar/bludit/releases/tag/2.0-beta7
Feel free to open a new ticket if you need it.
