### ISSUE TITLE
Cancel editing or creating content leads to wrong url

### ISSUE THREAD

**Issue by HarleyDavidson86** [dignajar/bludit#450]
No matter if you create a new content or edit an existing content:
After clicking the "Cancel" Button you get to a non existing page:

"Hey! Have you seen my ball?"

The URL is 
`"/bludit-2.0_a3/admin/manage-posts"` 
but it should be
`"/bludit-2.0_a3/admin/pages"`

**Comment by dignajar** [comment]
Fixed, thanks !
