### ISSUE TITLE
Empty title for pages get some words from the page content

### ISSUE THREAD

**Issue by dignajar** [dignajar/bludit#451]

**Comment by acrox999** [comment]
I am working on this. So far so good using the built-in helpers that you made. I'm thinking of 60 characters as the limit.

**Comment by acrox999** [comment]
I tried my best. It's been very long overdue. Please have a look.

**Comment by dignajar** [comment]
Is ok, but the title and the description is not good idea to get from content.

And I'm not sure about this part.
```
				$truncate = trim(mb_substr($string, 0, mb_strpos($string, ' ', $limit, CHARSET), CHARSET));
```

I need to test it on php 5.3.x.

**Comment by acrox999** [comment]
Right. I'm on 5.6 so I forgot about Bludit's compatibility goal.

**Comment by dignajar** [comment]
This feature was implemented on the latest beta version, please take a look https://github.com/dignajar/bludit/releases/tag/2.0-beta7
Feel free to open a new ticket if you need it.
