### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Sirjoseph94** [dignajar/bludit#466]
The latest release, v2.0 beta3 after installation displays 'page not found' even trying to access the admin area falsely displays same thing.

**Comment by dignajar** [comment]
Hi, could you look at the php_error.logs ? access_log from the webserver ? are you using Apache as a Webserver ?

**Comment by clickwork-git** [comment]
Is mod_rewrite installed and activated?

**Comment by Sirjoseph94** [comment]
Am using xampp it's my local development environment

**Comment by clickwork-git** [comment]
Then it seems to be an issue with the configuration of your local installation.

Is  mod_rewrite installed and activated?

**Comment by Turqueso** [comment]
I'm having the same issue, both locally and on a server. mod_rewrite is working.

**Comment by dignajar** [comment]
I fix some bugs, could you try the new beta, https://github.com/dignajar/bludit/releases/tag/2.0-beta4

**Comment by Sirjoseph94** [comment]
Cool. I will check it out soon and give feedback, thanks.

**Comment by Sirjoseph94** [comment]
i just checked the beta 4 on my local dev. using xampp still not working. yes my rewrite_mod

**Comment by Turqueso** [comment]
beta4 still shows the page not found error for me too

**Comment by dignajar** [comment]
someone can share the php_Error.log ?

**Comment by dignajar** [comment]
the .htaccess file is on the root ?

**Comment by Turqueso** [comment]
can't find php_Error.log and .htaccess is on root

**Comment by dignajar** [comment]
Let's try with the beta, https://github.com/dignajar/bludit/releases/tag/2.0-beta5

**Comment by ahmsar04** [comment]
This issue is back with Beta6
