### ISSUE TITLE
[Bludit 2 Beta 3] Fixed pages do not work

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#468]
Fixed pages do not work. The URL is shown in the browser, but it shows "Page not found".

**Comment by dignajar** [comment]
I fix some bugs, could you try the new beta, https://github.com/dignajar/bludit/releases/tag/2.0-beta4

**Comment by AlexL777** [comment]
Hello Developers,

I have just uploaded the beta 4 and have errors in the fixed pages in the sidebar.

The errors look like this. How can I fix it?

`
Fatal error: Uncaught Error: Call to undefined method dbPages::getFixedDB() in /xxxxxxxxxx/bludit.wpzweinull.ch/bl-plugins/fixed-pages/plugin.php:45 Stack trace: #0 /xxxxx/bludit.wpzweinull.ch/bl-kernel/helpers/theme.class.php(150): pluginFixedPages->siteSidebar() #1 /xxxxx/bludit.wpzweinull.ch/bl-themes/editorial/php/sidebar.php(1): Theme::plugins('siteSidebar') #2 /xxxxxxxx/bludit.wpzweinull.ch/bl-themes/editorial/index.php(59): include('/xxxxxxx...') #3 /xxxxxxx/bludit.wpzweinull.ch/bl-kernel/boot/site.php(25): include('/xxxxxxxx...') #4 /xxxxxx/bludit.wpzweinull.ch/index.php(39): require('/www/htdocs/w01...') #5 {main} thrown in /xxxxxxx/bludit.wpzweinull.ch/bl-plugins/fixed-pages/plugin.php on line 45
`

Thanks in advance.

**Comment by dignajar** [comment]
The issue is the plugin `fixed-pages` was renamed to `static-pages`, delete the old plugin from `bl-plugins/fixed-pages` folder.

**Comment by AlexL777** [comment]
Thanks for the hint, it had helped me very much and now everything again well.

**Comment by dignajar** [comment]
I close the ticket. Please take a look at the new beta version to check possibles fixes for the issue, https://github.com/dignajar/bludit/releases/tag/2.0-beta7

Feel free to open a new ticket if the problem persists with the latest version.
