### ISSUE TITLE
How do I have a Blog with Bludit 2.0

### ISSUE THREAD

**Issue by AlexL777** [dignajar/bludit#470]
Hello Developers,

I have Bludit 2.0 Beta 3 installed and found that only frontend pages are displayed. But how can I, for example, create a page called `/blog` and all blogposts end up on this page.

So far I have not understood it yet.

Maybe someone can help me.

Thanks in advance.

**Comment by Turqueso** [comment]
On Bludit 2, pages and posts are the same

**Comment by dignajar** [comment]
Hi,
just install Bludit v2.0, and create a new page, that it.
By default the content is ordered by date, so is a Blog.

If you need to create a Static page such as "About", "Contact", create a new page and on the menu Advanced->Status->Select Static.

Regards

**Comment by dignajar** [comment]
Check the new beta 4, https://github.com/dignajar/bludit/releases/tag/2.0-beta4

**Comment by Turqueso** [comment]
Just updated but the problem remains :/

**Comment by dignajar** [comment]
I close the ticket. Please take a look at the new beta version to check possibles fixes for the issue, https://github.com/dignajar/bludit/releases/tag/2.0-beta7

Feel free to open a new ticket if the problem persists with the latest version.
