### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by wi-wissen** [dignajar/bludit#478]
Hi,
without changing anything, my blog suddenly shows the following error: 

Fatal error: Call to a member function getField() on boolean in /_<full-path>_/bl-kernel/abstract/content.class.php on line 207

Adminpanel works fine.

What I tried:
- Update to newest version
- Reinstall newest version and restore backup
- change theme to https://github.com/bludit-themes/blogme

**Comment by wi-wissen** [comment]
My Solution:
Rollback to 1.1.2

users.php says my only user is wi-wissen
posts.php says all posts are written by admin and published 4 days before!

After creating user admin my posts are visible again.
Release dates are lost.

How could this happen?

**Comment by clickwork-git** [comment]
Which version was installed?

**Comment by wi-wissen** [comment]
Version 1.1.2

**Comment by clickwork-git** [comment]
It's an older version, and there were some problems with it.

First step: I would install the backup with 1.1.2. If this works we can see how to updgrade.

**Comment by wi-wissen** [comment]
Thank you for your replay.

I did your first step and found the error:
In posts.php I found that all posts are written 3 days before and the author is user "admin".
But thats not possible. I use the blog for two years and always use the user "wi-wissen".
After creating the user "admin" the error was gone.

So, everything is working again. Upgrade to newest stable version did also worked.

**Comment by clickwork-git** [comment]
Great! Thank you for the feedback!

**Comment by dignajar** [comment]
I close the ticket. Please take a look at the new beta version to check possibles fixes for the issue, https://github.com/dignajar/bludit/releases/tag/2.0-beta7

Feel free to open a new ticket if the problem persists with the latest version.
