### ISSUE TITLE
Language is saved but don't regon

### ISSUE THREAD

**Issue by Fred89** [dignajar/bludit#6]
The language is saved, but not loaded.

**Comment by Fred89** [comment]
I think lang is not stocked in sessions:

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /sites/projects/bludit/index.php:2) in /sites/projects/bludit/kernel/helpers/session.class.php on line 39

**Comment by dignajar** [comment]
Fixed! thanks
