### ISSUE TITLE
Notice when no sender is set in the settings

### ISSUE THREAD

**Issue by patschi** [dignajar/bludit#70]
Hi,

in 0.4 there is a little notice when no sender was set after upgrading from 0.3:
```
Notice: Undefined index: emailFrom in /path/kernel/dbsite.class.php on line 98
```

**Comment by dignajar** [comment]
Hi, just complete the field or left empty, and click on save button, on advanced settings, to regenerate the database.
Regards

**Comment by patschi** [comment]
Yeah, I filled out the field already. It worked fine. Just wanted to report you the notice anyway :)

**Comment by dignajar** [comment]
Yes thanks, I will add this warning on the forum..
