### ISSUE TITLE
Browser detection in install don't work

### ISSUE THREAD

**Issue by Fred89** [dignajar/bludit#73]
I Diego, the detection is broken in select lang page,
I tried with this 
``` php
// Try to detect language from HTTP
$locale = Locale::acceptFromHttp($_SERVER['HTTP_ACCEPT_LANGUAGE']);
$localeFromHTTP = $locale;
```

But is the same, return only 2 letter (en) and not en_US 
In a older bludit version i found the correct code.

**Comment by Fred89** [comment]
http://php.net/manual/en/locale.acceptfromhttp.php

**Comment by dignajar** [comment]
Hi Fred,
yes I know the method from Locale, but is a dependency more for the users,
there are servers does't have this function, and the locale is in the
variable $SERVER['HTTP_ACCEPT_LANGUAGE'], you don't need the function
Locale::acceptFromHttp to get the language.

Could you send me the information from $SERVER['HTTP_ACCEPT_LANGUAGE'],
where the function does't detect the language ?

<?php
var_dump($SERVER['HTTP_ACCEPT_LANGUAGE'])
?>

Thanks!

**Comment by Fred89** [comment]
I get NULL

**Comment by dignajar** [comment]
and this ?

<?php

var_dump( Locale::acceptFromHttp($*SERVER['HTTP_ACCEPT_LANGUAGE']) );*

var_dump($SERVER['HTTP_ACCEPT_LANGUAGE']);

?>

**Comment by Fred89** [comment]
bool(false) NULL

**Comment by dignajar** [comment]
The problem is no the current script because Locale::acceptFromHttp return
false too, is the server doesn't provide $SERVER variables.
I will make something with javascript, similar to autodetect the timezone.

**Comment by MegaBedder** [comment]
Try
```
<?php
echo '<pre>';
echo 'Browser: ' . $_SERVER['HTTP_USER_AGENT'];
echo PHP_EOL;
echo 'Browser Language: ' . $_SERVER['HTTP_ACCEPT_LANGUAGE'];
echo '</pre>';
?>
```

My output:
```
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
Browser Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3
```

Remember that the data sent by the browser are variable and change depending on the browser, so you can not trust that they are always sent.

In the event that the browser does not send the parameters, you should look for alternatives to detect the language or the language set by default in English.

**Comment by dignajar** [comment]
It already implemented with the variable HTTP_ACCEPT_LANGUAGE, but there are some web server doesn't get them.

**Comment by nickbe** [comment]
Is it possible to combine this with javascript detection:  'window.navigator.language' and 'navigator.userLanguage' for Internet Explorer?

**Comment by dignajar** [comment]
Hi,
I made some changes for detect the locale, language and timezone.

For timezone I used this library in javascript, http://pellepim.bitbucket.org/jstz/
For language and timezone I used PHP

```
	// Try to detect the locale
	if( function_exists('locale_accept_from_http') ) {
		$localeFromHTTP = locale_accept_from_http($_SERVER['HTTP_ACCEPT_LANGUAGE']);
	}
	else {
		$explodeLocale = explode(',', $_SERVER['HTTP_ACCEPT_LANGUAGE']);
		$localeFromHTTP = empty($explodeLocale[0])?'en_US':str_replace('-', '_', $explodeLocale[0]);
	}
```

**Comment by dignajar** [comment]
Improves on the latest version 1.1. I close the topic, feel free to open a new issues.
