### ISSUE TITLE
Admin URL must end with /

### ISSUE THREAD

**Issue by mciszczon** [dignajar/bludit#78]
Not sure, but guess this is a small bug.

When trying to access the admin panel, the URL must be something like this: `www.example.com/admin/` but when trying to access it with: `www.example.com/admin` it gives you 404 error.

Shouldn't both options be valid? Both ending with a slash and without it?

**Comment by dignajar** [comment]
Yes I think is a bug, because both are valid.
What version of Bludit are you using ?

**Comment by dignajar** [comment]
and what is your web server?

**Comment by mciszczon** [comment]
Yeah, I see on the demo site, that it works. Should've checked before posting and just look around myself. But anyway, it is interesting.

I use Bludit v0.4 (Ummagumma), I downloaded and installed it just yesterday. The server PHP version is **5.6.14** (checked also on 5.3).. It's actually a shared hosting, bought on www.hekko.pl (Polish site, you won't understand much).

Here's the list of active modules:
Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, mcrypt, mssql, standard, mysqlnd, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, Reflection, imap, SimpleXML, soap, sockets, mysqli, exif, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, mysql, litespeed, imagick, rar, hekko, dbase, geoip, oci8, mhash, ionCube Loader, Zend OPcache).

`.htaccess` is also working.

You may see the live site at: http://mciszczon.xyz/

**Comment by dignajar** [comment]
The "bug" is because the filter for admin area is "/admin/" then if the filter does not exist in the URL the admin area is jumped, and the filter for pages is taken.

If the server have this rule, DirectorySlash On, the directory /admin/ will add the slash at the end, and you can enter to admin area without the slash.

May be making a rewrite rule on htaccess, what do you think ?

**Comment by mciszczon** [comment]
Adding `DirectorySlash On` hasn't changed anything.

**Comment by Fred89** [comment]
I have the same with Mamp config:
Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zg DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0

**Comment by dignajar** [comment]
I made some changes on the URL system, now detect the /admin and /admin/

**Comment by anaggh** [comment]
Trying out the master branch now. It seems to work with and without '/' Thanks!
