### ISSUE TITLE
Warning & notice

### ISSUE THREAD

**Issue by Fred89** [dignajar/bludit#8]
Strict Standards: Declaration of dbUsers::get() should be compatible with dbJSON::get() in /sites/projects/bludit/kernel/dbusers.class.php on line 146

Strict Standards: Declaration of dbLanguage::get() should be compatible with dbJSON::get() in /sites/projects/bludit/kernel/dblanguage.class.php on line 91

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /sites/projects/bludit/kernel/dbusers.class.php:146) in /sites/projects/bludit/kernel/helpers/session.class.php on line 39

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /sites/projects/bludit/kernel/dbusers.class.php:146) in /sites/projects/bludit/kernel/helpers/session.class.php on line 39

**Comment by dignajar** [comment]
Fixed

**Comment by Fred89** [comment]
Yes !
