### ISSUE TITLE
localhost:8000 admin page 

### ISSUE THREAD

**Issue by jarnovanrhijn** [dignajar/bludit#85]
hi,

whenever i try accessing the bludit admin panel with http://localhost:8000/admin/ it says the page cannot be found. however if i add "core" `http://localhost:8000/core/admin` it goes to the login page but you cannot login. i've got mod_rewrite activated so this should not be the problem.

i'm running bludit on osx with `php -S localhost:8000`

i've tried to find the problem but was not able so far. i've also placed bludit on my server where it runs perfectly. so it's just on my local machine

**Comment by dignajar** [comment]
Hi,
what version do you installed ? it's a clean installation ? could you post the content of the file /content/databases/site.php

thanks

**Comment by jarnovanrhijn** [comment]
Hi,

i've got 0.5 installed. i is a clean install. this is the /content/databases/site.php content.

```json
{
    "title": "Bludit",
    "slogan": "cms",
    "description": "",
    "footer": "2015",
    "language": "en_US",
    "locale": "en_US",
    "timezone": "Europe\/London",
    "theme": "pure",
    "adminTheme": "default",
    "homepage": "",
    "postsperpage": "6",
    "uriPost": "\/post\/",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "url": "http:\/\/\/",
    "cliMode": "true",
    "emailFrom": "no-reply@"
} ```

**Comment by dignajar** [comment]
Its very strange the part when add the word "core" in the URL.

Try to complete the url field, with:

"url": "http:\/\/localhost\/",

**Comment by jarnovanrhijn** [comment]
Yeah i find it strange as well, especially because there is no reference to /core/admin anywhere. your solution didn't work either i'm afraid. on http://docs.bludit.com/en/troubleshooting/browser-returns-not-found the screenshot also links to the core path which probably is an older version but maybe it has something to do with it?

Also it's strange that on my server it works out of the box (with exactly the same code) where's on my local machine it doesn't. maybe my settings are incorrect somewhere?

**Comment by dignajar** [comment]
Yes on the image you can see core, because I have two version of Bludit on
my server, one called "core" and other "test".

Could you search this word "core"

$ cd {where you have bludit files}

$ grep -r "core" * --exclude="plugins/*"

**Comment by dignajar** [comment]
And the content of .htaccess must be.

AddDefaultCharset UTF-8

<IfModule mod_rewrite.c>

# Enable rewrite rules
RewriteEngine on

# Deny direct access to .txt files
RewriteRule ^content/(.*)\.txt$ - [R=404,L]

# All URL process by index.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*) index.php [PT,L]

</IfModule>

**Comment by jarnovanrhijn** [comment]
Tried both your suggestions but unfortunately they didn't work.

Will try to figure out where this comes from since there is no reference to "core" anywhere in the cms.

**Comment by jarnovanrhijn** [comment]
Maybe this will help?
http://stackoverflow.com/questions/9007513/php-5-4-built-in-server-fix-file-not-found-error

not sure if there is a router script available or needs to be added??

**Comment by dignajar** [comment]
Could you try with

php -S localhost:8000 index.php

On MAC OSx I used MAMPRO, this is a package with Apache and PHP

**Comment by jarnovanrhijn** [comment]
Yeah i've tried that before and but that just breaks other folders like css and js aswel as keeping the `core/admin` routing to the login page.

**Comment by jarnovanrhijn** [comment]
Maybe this helps? http://stackoverflow.com/questions/25031736/laravel4-the-requested-resource-admin-was-not-found-on-this-server

**Comment by jarnovanrhijn** [comment]
I've found that the word 'admin' is indeed the case why it says `The requested resource /admin/ was not found on this server.` changing this fixes the routing but i'm not sure why this is happening. i think this could cause certain bugs in the future.

**Comment by dignajar** [comment]
The problem is the name of the admin directory, I'm working on it, may be I will move the admin directory in /kernel/

**Comment by jarnovanrhijn** [comment]
Yeah i thought that was the case. anyways, hope this helps you and other people who have the same issues. Thanks for the great cms so far!!

**Comment by dignajar** [comment]
Done, I made the modifications to work with PHP built-in web server. Could you test it ? download the files from github. Just execute the command

```
php -S localhost:80
```

**Comment by dignajar** [comment]
Make a clean installation, because I moved the directory /admin/ into /kernel/admin/

**Comment by jarnovanrhijn** [comment]
Works like a charm!! thanks for the work and will continue testing Bludit!!
