### ISSUE TITLE
Pages sort

### ISSUE THREAD

**Issue by kaaleth** [dignajar/bludit#90]
![zrzut ekranu 8](https://cloud.githubusercontent.com/assets/3610174/11026441/42018038-86aa-11e5-909a-20ee4b7837ab.png)

Please take a look at that screen. It seems like pages do not sort properly when they have child.

**Comment by kaaleth** [comment]
Any?

**Comment by dignajar** [comment]
Yeap, seem like a bug.. I will check, thanks

**Comment by dignajar** [comment]
I made some changes on Github to fix this problem, could you try it ? thanks

**Comment by dignajar** [comment]
@kaaleth could you check this fix ? it on the latest version of Bludit v0.6.2

**Comment by kaaleth** [comment]
@dignajar yep, I am going to check this.

**Comment by kaaleth** [comment]
@dignajar 

Unfortunely, seems like does not work... :(

**Comment by dignajar** [comment]
Fixed on v1.3 beta 1.
