### ISSUE TITLE
Date of pages: only year saved

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#96]
In /content/databases/pages.php only the year is saved instead of the whole date.

**Comment by dignajar** [comment]
Fixed.I'm think the pages doesn't need the date of creation, because are a simple pages, with static content, If you need a page with a date you can use posts, but is my opinion.

**Comment by clickwork-git** [comment]
I'm insecure concerning the date of creation of a page... I agree that a page is static content. Although there should there be perhaps a field with the date of the last change.

**Comment by dignajar** [comment]
Can I close this topic ? It's solved on the last version ?
