### ISSUE TITLE
Problems with pages

### ISSUE THREAD

**Issue by clickwork-git** [dignajar/bludit#98]
There are sometimes pages that can only be saved, but there are no more buttons "Delete" and "Cancel". Also they cannot be assigned to a parent page.

Further assigning a page to a parent sometimes fails, after this the page also shows without the buttons "Delete" and "Cancel", and it can no more be assigned to a parent page.

No idea when this happens.

**Comment by dignajar** [comment]
If a page has a child then the page cannot be deleted (then the button delete doesn't showed).

I will check the problem when you try to assign a page as parent, any log on php_error.log ?

**Comment by clickwork-git** [comment]
Yes, the problem was, that still a page was assigned to it.

I will this add to the German tutorial for using the web interface.
